/* ニワラバトル v12 multi-format live battle engine.
 * Doubles / Triples / Full 6v6 / Tag (four trainers).
 * Keeps the legacy single engine untouched and uses the same shared data.
 */
(function(){
'use strict';
const D=window.NIWARA_DATA, API=()=>window.__PBV8;
if(!D) return;
const {SPECIES_DEX,MOVE_DEX,ITEM_DEX,NATURES,TYPE_CHART}=D;
const $=id=>document.getElementById(id);
const fmtSelect=$('battle-format-select'), modeSelect=$('battle-mode-select'), continueBtn=$('mode-continue-button');
const screen=$('format-battle-screen'), board=$('format-battle-board'), cmd=$('format-command-content'), logEl=$('format-battle-log');
if(!fmtSelect||!continueBtn||!screen) return;

const FORMATS=Object.freeze({
  double:{id:'double',name:'ダブル',select:4,active:2,trainersPerSide:1},
  triple:{id:'triple',name:'トリプル',select:6,active:3,trainersPerSide:1},
  full6:{id:'full6',name:'6vs6',select:6,active:1,trainersPerSide:1},
  tag:{id:'tag',name:'タッグ',select:3,active:2,trainersPerSide:2}
});
const ALL_FOES=new Set(['rock-slide','heat-wave','muddy-water','icy-wind','dazzling-gleam','hyper-voice','v6-068','v7-breaking-swipe','v7-struggle-bug','v7-electroweb']);
const ALL_ADJ=new Set(['earthquake','surf','discharge','v6-113','v7-explosion','v6-157','v6-136']);
const ALL_ALLIES=new Set(['v6-141','v6-153']);
const ALL_FIELD=new Set(['v6-024']);
const ALLY_SINGLE=new Set(['v6-107','v6-166']);
const SIDE_MOVES=new Set(['tailwind','v6-081','v6-140','v6-082','v6-023','v6-043','v6-044','v6-115','v7-toxic-spikes']);
const SELF_STATUS_HINT=new Set(['v6-072','protect','v6-017','v6-018','bulk-up','agility','iron-defense','nasty-plot','quiver-dance','rock-polish','recover','roost','moonlight','synthesis','calm-mind','swords-dance','v7-dragon-dance','v7-coil','v6-056','v6-086','v6-101','v6-102','v6-117','v6-124','v6-125','v6-133','v7-ant-march','v7-bubble-guard','v7-ingrain','v7-seishin-toitsu']);
const FORMAT_LABEL={single:'シングル',double:'ダブル',triple:'トリプル',full6:'6vs6',tag:'タッグ'};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const clone=o=>JSON.parse(JSON.stringify(o));
let state=null, selectionSession=null, autoplayTimer=null;

function sp(id){return SPECIES_DEX[id];}
function mv(id){return MOVE_DEX[id];}
function item(id){return ITEM_DEX[id]||ITEM_DEX.none||{id:'none',name:'なし'};}
function natureMult(name,stat){const n=NATURES[name]||NATURES['まじめ'];return n?.up===stat?1.1:n?.down===stat?0.9:1;}
function statValue(base,pt,nat,stat){return Math.floor((base+clamp(Number(pt)||0,0,32)+20)*natureMult(nat,stat));}
function hpValue(base,pt){return base+clamp(Number(pt)||0,0,32)+75;}
function stageMult(x){x=clamp(x||0,-6,6);return x>=0?(2+x)/2:2/(2-x);}
function typeEff(type,types,attAbility){let m=1;for(const t of types){let x=TYPE_CHART?.[type]?.[t];if(x==null)x=1;if(x===0&&t==='ゴースト'&&attAbility==='scrappy'&&['ノーマル','かくとう'].includes(type))x=1;m*=x;}return m;}
function effectiveSpeed(p){let x=Math.floor(p.speed*stageMult(p.stages.speed));if(p.status==='paralysis')x=Math.floor(x*.5);if(activeItem(p)&&p.item.id==='choice-scarf')x=Math.floor(x*1.5);if(state.field.tailwind[p.side]>0)x*=2;return Math.max(1,x);}
function activeItem(p){return !p.itemConsumed&&state?.field?.magicRoom<=0;}
function percent(p){return p.maxHP?Math.max(0,Math.round(p.hp/p.maxHP*100)):0;}
function makePokemon(set,trainerId,side,index){const s=sp(set.speciesId),pts=set.statPoints||{},nat=set.nature||'まじめ';const p={uid:`${trainerId}-${index}-${Math.random().toString(36).slice(2,7)}`,trainerId,side,set:clone(set),id:s.id,name:s.name,types:[...s.types],ability:clone(s.abilities.find(a=>a.id===set.abilityId)||s.abilities[0]),item:clone(item(set.itemId)),nature:nat,maxHP:hpValue(s.baseStats.hp,pts.hp),hp:0,attack:statValue(s.baseStats.attack,pts.attack,nat,'attack'),defense:statValue(s.baseStats.defense,pts.defense,nat,'defense'),specialAttack:statValue(s.baseStats.specialAttack,pts.specialAttack,nat,'specialAttack'),specialDefense:statValue(s.baseStats.specialDefense,pts.specialDefense,nat,'specialDefense'),speed:statValue(s.baseStats.speed,pts.speed,nat,'speed'),moves:set.moves.map(id=>{const m=mv(id);return m?{...m,pp:m.maxPP??m.pp??10,maxPP:m.maxPP??m.pp??10}:null;}).filter(Boolean),status:null,statusTurns:0,toxicCounter:1,stages:{attack:0,defense:0,specialAttack:0,specialDefense:0,speed:0,accuracy:0,evasion:0},itemConsumed:false,recharge:false,protect:false,choiceLock:null,charging:null,lastMoveId:null,seen:false,knownMoves:new Set(),abilityRevealed:false,itemRevealed:false,fainted:false,position:null};p.hp=p.maxHP;return p;}
function trainer(id,side,label,controller,difficulty,roster,selected){const team=selected.map((ri,i)=>makePokemon(roster[ri],id,side,i));return{id,side,label,controller,difficulty,roster,selected,team,active:[],knowledge:{},pending:[],human:controller==='human'};}
function currentBuilder(){return clone(API()?.builderSets||[]);}
function savedPartyById(id){return clone(API()?.savedParties?.find(p=>p.id===id)?.sets||[]);}
function sourceOptions(){const out=[{value:'current',text:'現在の編成'},{value:'random',text:'強化ランダムCPU構築'}];for(const p of API()?.savedParties||[])out.push({value:`saved:${p.id}`,text:`保存：${p.name}`});return out;}
function resolveSource(value){if(value==='current')return currentBuilder();if(value==='random')return clone(API()?.buildStrongRandomTeam?.()||currentBuilder());if(value?.startsWith('saved:'))return savedPartyById(value.slice(6));const direct=savedPartyById(value);if(Array.isArray(direct)&&direct.length===6)return direct;return currentBuilder();}
function cpuSelect(roster,count,difficulty,oppRoster=[]){if(count>=6)return [0,1,2,3,4,5].sort((a,b)=>leadScore(roster[b])-leadScore(roster[a]));let base=[];try{base=API()?.chooseCpuSelection?.(roster,oppRoster,difficulty)||[];}catch(_){base=[];}const rest=[0,1,2,3,4,5].filter(i=>!base.includes(i)).sort((a,b)=>leadScore(roster[b])-leadScore(roster[a]));return [...base,...rest].slice(0,count);}
function leadScore(set){const s=sp(set.speciesId);return (s?.baseStats?.speed||0)*1.1+Math.max(s?.baseStats?.attack||0,s?.baseStats?.specialAttack||0)+(s?.baseStats?.hp||0)*.25;}
function log(text,kind='',meta=null){if(!state)return;state.logs.push({text,kind,turn:state.turn,meta});if(state.logs.length>500)state.logs.shift();renderLog();}
function trainerById(id){return state?.trainers.find(t=>t.id===id);}
function sideTrainers(side){return state.trainers.filter(t=>t.side===side);}
function sideActives(side){return sideTrainers(side).flatMap(t=>t.active).filter(p=>p&&p.hp>0);}
function allActives(){return [...sideActives('A'),...sideActives('B')];}
function aliveTrainer(t){return t.team.some(p=>p.hp>0);}
function aliveSide(side){return sideTrainers(side).some(aliveTrainer);}
function bench(t){return t.team.filter(p=>p.hp>0&&!t.active.includes(p));}
function sideBench(side){return sideTrainers(side).flatMap(bench);}
function otherSide(side){return side==='A'?'B':'A';}
function targetMode(move){if(ALL_FIELD.has(move.id))return'all-field';if(ALL_ADJ.has(move.id))return'all-adjacent';if(ALL_FOES.has(move.id))return'all-foes';if(ALL_ALLIES.has(move.id))return'all-allies';if(ALLY_SINGLE.has(move.id))return'ally';if(SIDE_MOVES.has(move.id)||move.weather||move.terrain||move.screen||move.tailwind||move.trickRoom||move.hazard)return'side';if(move.category==='status'&&(SELF_STATUS_HINT.has(move.id)||move.selfStatChanges||move.healRatio||move.rest||move.protect||move.substitute))return'self';return'foe';}
function tripleAdjacent(a,b){if(state.format.id!=='triple')return true;if(a.side===b.side)return Math.abs((a.position??0)-(b.position??0))<=1;return Math.abs((a.position??0)-(b.position??0))<=1;}
function legalTargets(actor,move){const mode=targetMode(move);if(mode==='self')return[actor];if(mode==='side'||mode==='all-field')return[];if(mode==='ally')return sideActives(actor.side).filter(x=>x!==actor&&tripleAdjacent(actor,x));if(mode==='all-allies')return sideActives(actor.side);if(mode==='all-foes')return sideActives(otherSide(actor.side)).filter(x=>tripleAdjacent(actor,x));if(mode==='all-adjacent')return allActives().filter(x=>x!==actor&&tripleAdjacent(actor,x));return sideActives(otherSide(actor.side)).filter(x=>tripleAdjacent(actor,x));}
function isSpread(move,targets){return ['all-adjacent','all-foes','all-allies'].includes(targetMode(move))&&targets.length>1;}
function accuracy(move,a,d){if(move.accuracy==null)return true;let acc=move.accuracy;if(state.field.weather==='rain'&&move.id==='thunder')acc=100;if(state.field.weather==='snow'&&move.id==='v6-010')acc=100;const am=a.stages.accuracy||0,ev=d?.stages?.evasion||0;const mult=x=>x>=0?(3+x)/3:3/(3-x);return Math.random()*100<acc*mult(am)/mult(ev);}
function critChance(move){return move.highCrit?1/8:1/24;}
function calcPower(a,d,move){let power=Number(move.power)||0;if(move.id==='v6-005'||move.id==='v6-122')power=d?Math.max(20,Math.min(120,Math.floor((sp(d.id)?.weight||50)/20)*20)):60;if(move.id==='v6-126')power=d?Math.max(1,Math.floor(100*d.hp/d.maxHP)):100;if(move.id==='v6-150')power=a.hp/a.maxHP<=.041?200:a.hp/a.maxHP<=.104?150:a.hp/a.maxHP<=.208?100:a.hp/a.maxHP<=.354?80:a.hp/a.maxHP<=.687?40:20;if(move.id==='v6-158')power=20+20*Object.values(a.stages).filter(x=>x>0).reduce((s,x)=>s+x,0);if(move.id==='v6-174'&&state.field.terrain==='electric')power*=2;return power;}
function damageRoll(a,d,move,spread=false,critical=false,model=false){let power=calcPower(a,d,move);if(!power)return 0;let cat=move.category;if(move.id==='v7-golden-burn')cat=a.attack>=a.specialAttack?'physical':'special';let atk=cat==='physical'?a.attack:a.specialAttack,def=cat==='physical'?d.defense:d.specialDefense;let astage=cat==='physical'?a.stages.attack:a.stages.specialAttack,dstage=cat==='physical'?d.stages.defense:d.stages.specialDefense;if(critical){astage=Math.max(0,astage);dstage=Math.min(0,dstage);}atk=Math.max(1,Math.floor(atk*stageMult(astage)));def=Math.max(1,Math.floor(def*stageMult(dstage)));if(cat==='physical'&&a.status==='burn'&&move.id!=='v6-093')atk=Math.max(1,Math.floor(atk*.5));if(a.ability.id==='fur-coat'&&cat==='physical'){}if(d.ability.id==='fur-coat'&&cat==='physical')def*=2;if(move.id==='body-press'||move.id==='v7-pumpkin-press'){atk=Math.floor(a.defense*stageMult(a.stages.defense));}let base=Math.floor(Math.floor(Math.floor((2*50/5+2)*power*atk/def)/50)+2);let mod=1;if(a.types.includes(move.type))mod*=a.ability.id==='adaptability'?2:1.5;let eff=typeEff(move.type,d.types,a.ability.id);if(d.ability.id==='levitate'&&move.type==='じめん')eff=0;if(d.ability.id==='earth-eater'&&move.type==='じめん')eff=0;if(d.ability.id==='lightning-rod'&&move.type==='でんき')eff=0;if(d.ability.id==='sap-sipper'&&move.type==='くさ')eff=0;if(a.ability.id==='tinted-lens'&&eff>0&&eff<1)eff*=2;mod*=eff;if(state.field.weather==='rain'){if(move.type==='みず')mod*=1.5;if(move.type==='ほのお')mod*=.5;}if(state.field.weather==='sun'){if(move.type==='ほのお')mod*=1.5;if(move.type==='みず')mod*=.5;}if(a.ability.id==='water-bubble'&&move.type==='みず')mod*=2;if(d.ability.id==='water-bubble'&&move.type==='ほのお')mod*=.5;if(a.ability.id==='fairy-aura'&&move.type==='フェアリー')mod*=4/3;if(activeItem(a)&&a.item.id==='life-orb')mod*=1.3;if(activeItem(a)&&a.item.id==='choice-band'&&cat==='physical')mod*=1.5;if(activeItem(a)&&a.item.id==='choice-specs'&&cat==='special')mod*=1.5;if(activeItem(a)&&a.item.id==='expert-belt'&&eff>1)mod*=1.2;if(spread)mod*=.75;const sc=state.field.screens[d.side];if(!critical&&cat==='physical'&&sc.reflect>0)mod*=state.format.active>1?2/3:.5;if(!critical&&cat==='special'&&sc.lightScreen>0)mod*=state.format.active>1?2/3:.5;if(critical)mod*=1.5;const rand=model?.92:(.85+Math.random()*.15);return Math.max(eff===0?0:1,Math.floor(base*mod*rand));}
function consumeResistBerry(d,move,eff,damage){if(!activeItem(d))return damage;const map={'occa-berry':'ほのお','passho-berry':'みず','wacan-berry':'でんき','rindo-berry':'くさ','yache-berry':'こおり','chople-berry':'かくとう','kebia-berry':'どく','shuca-berry':'じめん','coba-berry':'ひこう','payapa-berry':'エスパー','tanga-berry':'むし','charti-berry':'いわ','kasib-berry':'ゴースト','haban-berry':'ドラゴン','colbur-berry':'あく','babiri-berry':'はがね','roseli-berry':'フェアリー'};if(d.item.id==='chilan-berry'&&move.type==='ノーマル'){d.itemRevealed=true;d.itemConsumed=true;log(`${d.name}は ${d.item.name}でダメージを弱めた！`);return Math.max(1,Math.floor(damage/2));}if(map[d.item.id]===move.type&&eff>1){d.itemRevealed=true;d.itemConsumed=true;log(`${d.name}は ${d.item.name}で${move.type}技を弱めた！`);return Math.max(1,Math.floor(damage/2));}return damage;}
function changeStages(p,changes){if(!changes)return;for(const [k,v] of Object.entries(changes))p.stages[k]=clamp((p.stages[k]||0)+v,-6,6);}
function applyStatus(p,status,chance=100){if(p.status||p.hp<=0||Math.random()*100>=chance)return false;if(status==='burn'&&p.types.includes('ほのお'))return false;if(['poison','toxic'].includes(status)&&(p.types.includes('どく')||p.types.includes('はがね')))return false;if(status==='paralysis'&&p.types.includes('でんき'))return false;if(status==='freeze'&&p.types.includes('こおり'))return false;if(status==='burn'&&p.ability.id==='water-bubble')return false;p.status=status;if(status==='sleep')p.statusTurns=2;if(status==='toxic')p.toxicCounter=1;log(`${p.name}は ${D.STATUS_NAMES?.[status]||status}状態になった！`);return true;}
function heal(p,n,why='回復'){const before=p.hp;p.hp=Math.min(p.maxHP,p.hp+Math.max(0,Math.floor(n)));const x=p.hp-before;if(x>0)log(`${p.name}は ${x} HP ${why}した！`,'',{hpChange:'heal',targetUid:p.uid,targetSide:p.side,targetTrainerId:p.trainerId,name:p.name,amount:x,maxHP:p.maxHP,reason:why});}
function hurt(p,n,why='ダメージ'){const before=p.hp;p.hp=Math.max(0,p.hp-Math.max(0,Math.floor(n)));const x=before-p.hp;if(x>0)log(`${p.name}は ${x} ${why}！`,'',{hpChange:'damage',targetUid:p.uid,targetSide:p.side,targetTrainerId:p.trainerId,name:p.name,amount:x,maxHP:p.maxHP,reason:why});if(p.hp<=0&&!p.fainted){p.fainted=true;log(`${p.name}は たおれた！`);}return x;}
function setWeather(w){state.field.weather=w;state.field.weatherTurns=5;log(`天候が ${D.WEATHER_NAMES?.[w]||w} になった！`);}
function entry(p){p.seen=true;p.position=p.position??0;const ab=p.ability.id;if(['drizzle','sand-stream','fairy-aura'].includes(ab))p.abilityRevealed=true;if(ab==='drizzle')setWeather('rain');if(ab==='sand-stream')setWeather('sand');if(ab==='fairy-aura')log(`${p.name}の フェアリーオーラが発動した！`);const hz=state.field.hazards[p.side];if(hz.stealthRock){const e=typeEff('いわ',p.types,null);hurt(p,Math.max(1,Math.floor(p.maxHP*e/8)),'ステルスロックのダメージ');}if(hz.spikes&&!p.types.includes('ひこう')&&ab!=='levitate')hurt(p,Math.max(1,Math.floor(p.maxHP*(hz.spikes>=3?.25:hz.spikes===2?1/6:.125))),'まきびしのダメージ');if(hz.stickyWeb&&!p.types.includes('ひこう')&&ab!=='levitate')p.stages.speed=clamp(p.stages.speed-1,-6,6);}
function activateInitial(t){const n=state.format.id==='tag'?1:state.format.active;t.active=t.team.slice(0,n);t.active.forEach((p,i)=>{p.position=state.format.id==='tag'?sideTrainers(t.side).findIndex(x=>x.id===t.id):i;entry(p);});}
function sideSlotEntries(side){return sideTrainers(side).flatMap(t=>t.active.map((p,i)=>({trainer:t,p,slot:i,pos:p.position??i})));}
function targetLabel(p){return `${trainerById(p.trainerId)?.label||p.side}：${p.name} (${percent(p)}%)`;}
function applyMove(actor,move,targetChoice){const t=trainerById(actor.trainerId);if(actor.hp<=0)return;if(actor.recharge){actor.recharge=false;log(`${actor.name}は 反動で動けない！`);return;}if(actor.status==='sleep'){if(actor.statusTurns>0){actor.statusTurns--;log(`${actor.name}は 眠っている…`);return;}actor.status=null;}if(actor.status==='paralysis'&&Math.random()<.25){log(`${actor.name}は まひして動けない！`);return;}if(actor.charging?.moveId===move.id){actor.charging=null;}else if(move.twoTurn&&!((activeItem(actor)&&actor.item.id==='power-herb')||(move.solar&&state.field.weather==='sun')||(move.electroShot&&state.field.weather==='rain'))){actor.charging={moveId:move.id,targetUid:targetChoice?.uid||null};if(move.selfStatChanges)changeStages(actor,move.selfStatChanges);log(`${actor.name}は ${move.name}の準備を始めた！`);return;}else if(move.twoTurn&&activeItem(actor)&&actor.item.id==='power-herb'){actor.itemConsumed=true;log(`${actor.name}は パワフルハーブで即座に攻撃する！`);}const own=actor.moves.find(x=>x.id===move.id);if(own&&own.pp>0)own.pp--;actor.lastMoveId=move.id;actor.knownMoves.add(move.id);log(`${actor.name}の ${move.name}！`);
  if(move.protect||move.protectLike){actor.protect=true;return;}if(move.id==='v6-072'){state.redirector[actor.side]=actor;log(`${actor.name}は 攻撃を引きつけている！`);return;}if(move.id==='v6-087'){state.quickGuard[actor.side]=true;log(`${trainerById(actor.trainerId)?.label||actor.side}側は先制技から守られている！`);return;}if(move.healRatio&&targetMode(move)==='self'){heal(actor,Math.floor(actor.maxHP*move.healRatio));return;}if(move.rest){actor.status='sleep';actor.statusTurns=2;actor.hp=actor.maxHP;return;}if(move.weather){setWeather(move.weather);return;}if(move.terrain){state.field.terrain=move.terrain;state.field.terrainTurns=5;log(`フィールドが ${move.terrain} になった！`);return;}if(move.trickRoom){state.field.trickRoom=5;log('時空がゆがんだ！');return;}if(move.tailwind){state.field.tailwind[actor.side]=4;return;}if(move.screen){state.field.screens[actor.side][move.screen]=5;return;}if(move.hazard){const hz=state.field.hazards[otherSide(actor.side)];if(move.hazard==='stealthRock')hz.stealthRock=true;if(move.hazard==='spikes')hz.spikes=Math.min(3,(hz.spikes||0)+1);if(move.hazard==='stickyWeb')hz.stickyWeb=true;if(move.hazard==='toxicSpikes')hz.toxicSpikes=Math.min(2,(hz.toxicSpikes||0)+1);return;}if(move.selfStatChanges&&move.category==='status'){changeStages(actor,move.selfStatChanges);return;}
  let targets=legalTargets(actor,move);const mode=targetMode(move);if(['foe','ally'].includes(mode)){let chosen=targets.find(x=>x.uid===targetChoice?.uid)||targets[0];if(mode==='foe'&&chosen){const redir=state.redirector[chosen.side];if(redir&&redir.hp>0&&tripleAdjacent(actor,redir)&&move.type!=='くさ'){chosen=redir;log(`${redir.name}が 攻撃を引きつけた！`);}}targets=chosen?[chosen]:[];}if(mode==='self')targets=[actor];if(mode==='side')targets=[];if(mode==='all-field'){targets=allActives();}if(mode==='all-allies')targets=sideActives(actor.side);if(!targets.length&&move.category!=='status'){log('しかし 対象がいない！');return;}const spread=isSpread(move,targets);
  if(move.category==='status'){
    for(const d of targets){if(d.protect&&d.side!==actor.side&&!move.ignoreProtect){log(`${d.name}は 攻撃を防いだ！`);continue;}if(!accuracy(move,actor,d)){log(`${d.name}には 当たらなかった！`);continue;}if(move.directStatus)applyStatus(d,move.directStatus);if(move.toxic)applyStatus(d,'toxic');if(move.targetStatChanges)changeStages(d,move.targetStatChanges);if(move.confuseChance&&Math.random()*100<move.confuseChance)log(`${d.name}は こんらんした！`);if(move.healTargetRatio)heal(d,Math.floor(d.maxHP*move.healTargetRatio));if(move.id==='v6-141')heal(d,Math.floor(d.maxHP/4));if(move.id==='v6-107')d.helpingHand=true;if(move.id==='v6-153'){changeStages(d,{attack:1,defense:1});}}
    return;
  }
  let totalDealt=0;
  for(const d of targets){if(d.hp<=0)continue;if(state.quickGuard[d.side]&&(move.priority||0)>0&&!move.feint){log(`${d.name}への先制技は ファストガードで防がれた！`);continue;}if(d.protect&&!move.feint&&!move.ignoreProtect){log(`${d.name}は 攻撃を防いだ！`);continue;}if(!accuracy(move,actor,d)){log(`${d.name}には 当たらなかった！`);continue;}const crit=Math.random()<critChance(move);let eff=typeEff(move.type,d.types,actor.ability.id);let dmg=damageRoll(actor,d,move,spread,crit);dmg=consumeResistBerry(d,move,eff,dmg);if(actor.helpingHand){dmg=Math.floor(dmg*1.5);actor.helpingHand=false;}const before=d.hp;if(dmg>=d.hp&&d.hp===d.maxHP){if(d.ability.id==='sturdy'){dmg=d.hp-1;log(`${d.name}は がんじょうで耐えた！`);}else if(activeItem(d)&&d.item.id==='focus-sash'){d.itemRevealed=true;d.itemConsumed=true;dmg=d.hp-1;log(`${d.name}は きあいのタスキで耐えた！`);}}const dealt=hurt(d,dmg,'ダメージ');totalDealt+=dealt;if(crit)log('急所に当たった！');if(eff>1)log('効果はばつぐんだ！');else if(eff>0&&eff<1)log('効果はいまひとつだ…');else if(eff===0)log('効果がないようだ…');if(move.targetStatChanges&&d.hp>0)changeStages(d,move.targetStatChanges);if(move.targetStatChangeChance&&d.hp>0&&Math.random()*100<move.targetStatChangeChance.chance)changeStages(d,{[move.targetStatChangeChance.stat]:move.targetStatChangeChance.amount});if(move.secondaryStatus&&d.hp>0)applyStatus(d,move.secondaryStatus.status,move.secondaryStatus.chance);if(move.flinchChance&&d.hp>0&&Math.random()*100<move.flinchChance)d.flinched=true;}
  if(move.selfStatChanges)changeStages(actor,move.selfStatChanges);if(move.selfStatChangeChance&&Math.random()*100<move.selfStatChangeChance.chance)changeStages(actor,{[move.selfStatChangeChance.stat]:move.selfStatChangeChance.amount});if(move.drainRatio&&totalDealt>0)heal(actor,Math.max(1,Math.floor(totalDealt*move.drainRatio)));if(move.recoilRatio&&totalDealt>0&&actor.ability.id!=='magic-guard')hurt(actor,Math.max(1,Math.round(totalDealt*move.recoilRatio)),'反動ダメージ');if(move.recoilMaxHPRatio&&actor.ability.id!=='magic-guard')hurt(actor,Math.max(1,Math.ceil(actor.maxHP*move.recoilMaxHPRatio)),'反動ダメージ');if(activeItem(actor)&&actor.item.id==='life-orb'&&totalDealt>0&&actor.ability.id!=='magic-guard'){actor.itemRevealed=true;hurt(actor,Math.max(1,Math.floor(actor.maxHP/10)),'いのちのたまの反動');}if(move.selfFaint||move.selfFaintAfterDamage)hurt(actor,actor.hp,'反動');if(move.recharge&&totalDealt>0)actor.recharge=true;if(activeItem(actor)&&['choice-band','choice-specs','choice-scarf'].includes(actor.item.id))actor.choiceLock=move.id;if(move.pivot&&actor.hp>0){const b=bench(t);if(b.length){if(t.controller==='cpu'){switchPokemon(t,actor,bestBench(t));}else{state.pendingPivot={trainer:t,actor,options:b};return 'pivot-pending';}}}
}
function switchPokemon(t,oldP,newP){if(!newP||newP.hp<=0||t.active.includes(newP))return false;const idx=t.active.indexOf(oldP),pos=oldP.position;if(idx<0)return false;if(oldP.ability.id==='regenerator')oldP.hp=Math.min(oldP.maxHP,oldP.hp+Math.floor(oldP.maxHP/3));oldP.choiceLock=null;oldP.charging=null;oldP.recharge=false;oldP.protect=false;oldP.flinched=false;t.active[idx]=newP;newP.position=pos;newP.protect=false;entry(newP);log(`${t.label}は ${newP.name}を繰り出した！`);return true;}
function bestBench(t){return bench(t).sort((a,b)=>percent(b)-percent(a))[0]||null;}
function applyResidual(p){if(p.hp<=0)return;if(p.status==='burn')hurt(p,Math.max(1,Math.floor(p.maxHP/16)),'やけどのダメージ');if(p.status==='poison')hurt(p,Math.max(1,Math.floor(p.maxHP/8)),'どくのダメージ');if(p.status==='toxic'){hurt(p,Math.max(1,Math.floor(p.maxHP*p.toxicCounter/16)),'もうどくのダメージ');p.toxicCounter=Math.min(15,p.toxicCounter+1);}if(p.hp>0&&activeItem(p)&&p.item.id==='leftovers'){p.itemRevealed=true;heal(p,Math.max(1,Math.floor(p.maxHP/16)));}if(p.hp>0&&activeItem(p)&&p.item.id==='sitrus-berry'&&p.hp<=p.maxHP/2){p.itemRevealed=true;p.itemConsumed=true;heal(p,Math.max(1,Math.floor(p.maxHP/4)),'回復');}if(p.hp>0&&p.ability.id==='poison-heal'&&['poison','toxic'].includes(p.status))heal(p,Math.max(1,Math.floor(p.maxHP/8)));if(p.hp>0&&p.ability.id==='speed-boost')p.stages.speed=clamp(p.stages.speed+1,-6,6);p.protect=false;p.flinched=false;}
function tickField(){if(state.field.weatherTurns>0&&--state.field.weatherTurns<=0)state.field.weather=null;if(state.field.terrainTurns>0&&--state.field.terrainTurns<=0)state.field.terrain=null;if(state.field.trickRoom>0)state.field.trickRoom--;if(state.field.magicRoom>0)state.field.magicRoom--;for(const side of ['A','B']){if(state.field.tailwind[side]>0)state.field.tailwind[side]--;for(const k of ['reflect','lightScreen'])if(state.field.screens[side][k]>0)state.field.screens[side][k]--;}}
function actionOrder(actions){return [...actions].sort((x,y)=>{if(x.type==='switch'&&y.type!=='switch')return-1;if(y.type==='switch'&&x.type!=='switch')return 1;const px=x.type==='move'?(mv(x.moveId)?.priority||0):0,py=y.type==='move'?(mv(y.moveId)?.priority||0):0;if(px!==py)return py-px;const sx=effectiveSpeed(x.actor),sy=effectiveSpeed(y.actor);if(sx===sy)return Math.random()<.5?-1:1;return state.field.trickRoom>0?sx-sy:sy-sx;});}
function cpuModelTarget(p){const s=sp(p.id),base=s.baseStats,estHP=base.hp+91;return{id:p.id,name:p.name,side:p.side,types:[...s.types],ability:{id:p.abilityRevealed?p.ability.id:'unknown'},item:{id:p.itemRevealed&&!p.itemConsumed?p.item.id:'none'},itemConsumed:!p.itemRevealed||p.itemConsumed,nature:'まじめ',maxHP:estHP,hp:Math.max(1,Math.round(estHP*percent(p)/100)),attack:base.attack+36,defense:base.defense+36,specialAttack:base.specialAttack+36,specialDefense:base.specialDefense+36,speed:base.speed+36,status:p.status,stages:{...p.stages}};}
function cpuChoose(actor,t){if(actor.charging){const m=mv(actor.charging.moveId);return{type:'move',actor,moveId:m.id,targetUid:actor.charging.targetUid};}if(actor.recharge)return{type:'move',actor,moveId:actor.moves[0]?.id};const foes=sideActives(otherSide(actor.side));const moves=actor.moves.filter(m=>m.pp>0&&(!actor.choiceLock||actor.choiceLock===m.id));let best=null,bestScore=-1e9;for(const m of moves){const mode=targetMode(m);let targets=legalTargets(actor,m);const candidateTargets=['foe','ally'].includes(mode)?targets:[null];if(!candidateTargets.length)candidateTargets.push(null);for(const tar of candidateTargets){let score=0;if(m.category!=='status'){const ts=['foe','ally'].includes(mode)?[tar].filter(Boolean):targets;for(const x of ts){if(!x)continue;const model=cpuModelTarget(x);const dmg=damageRoll(actor,model,m,isSpread(m,ts),false,true);score+=dmg/model.maxHP*100;if(dmg>=model.hp)score+=55;}if(isSpread(m,ts))score+=8;if(m.recoilRatio||m.selfFaint||m.recharge)score-=actor.hp/actor.maxHP<.45?30:8;if(m.priority>0)score+=8;}else{if(m.healRatio)score+=actor.hp/actor.maxHP<.5?45:5;if(m.selfStatChanges)score+=18;if(m.tailwind||m.screen||m.trickRoom)score+=22;if(m.directStatus||m.toxic)score+=15;if(m.protect)score+=10;}if(t.difficulty==='normal')score+=Math.random()*35;if(t.difficulty==='strong')score+=Math.random()*12;if(score>bestScore){bestScore=score;best={type:'move',actor,moveId:m.id,targetUid:tar?.uid||null};}}}
  if(t.difficulty!=='normal'&&percent(actor)<28&&bench(t).length&&bestScore<75){const b=bestBench(t);if(b)return{type:'switch',actor,switchUid:b.uid};}return best||{type:'move',actor,moveId:actor.moves[0]?.id,targetUid:foes[0]?.uid||null};}
function replaceFaintsAuto(){let needsHuman=[];for(const t of state.trainers){for(let i=0;i<t.active.length;i++){const p=t.active[i];if(p&&p.hp<=0){const options=bench(t);if(!options.length)continue;if(t.controller==='cpu'){const n=bestBench(t);t.active[i]=n;n.position=p.position;entry(n);log(`${t.label}は ${n.name}を繰り出した！`);}else needsHuman.push({trainer:t,slot:i,old:p,options});}}}return needsHuman;}
function resolveTurn(){state.phase='resolving';state.resolutionQueue=actionOrder(state.actions);state.resolutionIndex=0;render();continueResolveTurn();}
function continueResolveTurn(){
  if(!state||state.over)return;
  const q=state.resolutionQueue||[];
  while(state.resolutionIndex<q.length){
    const a=q[state.resolutionIndex++];if(!a?.actor||a.actor.hp<=0)continue;const t=trainerById(a.actor.trainerId);let pause=false;
    if(a.type==='switch'){const n=t.team.find(p=>p.uid===a.switchUid);switchPokemon(t,a.actor,n);}else if(a.type==='move'){
      if(a.actor.flinched){log(`${a.actor.name}は ひるんで動けない！`);a.actor.flinched=false;continue;}
      pause=applyMove(a.actor,mv(a.moveId),a.targetUid?allPokemon().find(p=>p.uid===a.targetUid):null)==='pivot-pending';
    }
    if(checkWinner()){finishBattle();return;}
    if(pause){promptPivotChoice();return;}
  }
  state.resolutionQueue=[];state.resolutionIndex=0;
  if(!checkWinner()){for(const p of [...allActives()].sort((a,b)=>effectiveSpeed(b)-effectiveSpeed(a)))applyResidual(p);tickField();}
  if(checkWinner()){finishBattle();return;}const needs=replaceFaintsAuto();if(checkWinner()){finishBattle();return;}if(needs.length){state.replacements=needs;state.replacementIndex=0;promptReplacement();return;}state.turn++;startCommandPhase();
}
function promptPivotChoice(){const r=state.pendingPivot;if(!r){continueResolveTurn();return;}state.phase='pivot';state.currentHuman=r.trainer.id;render();cmd.replaceChildren();const h=document.createElement('h3');h.textContent=`${r.trainer.label}：${r.actor.name}の交代先を選択`;cmd.appendChild(h);const g=document.createElement('div');g.className='switch-grid';for(const p of bench(r.trainer)){const b=document.createElement('button');b.className='switch-button';b.textContent=`${p.name} HP ${percent(p)}%`;b.onclick=()=>{if(!switchPokemon(r.trainer,r.actor,p))return;state.pendingPivot=null;continueResolveTurn();};g.appendChild(b);}cmd.appendChild(g);}

function allPokemon(){return state.trainers.flatMap(t=>t.team);}
function checkWinner(){const a=aliveSide('A'),b=aliveSide('B');state.winner=a&&!b?'A':b&&!a?'B':!a&&!b?'draw':null;return !!state.winner;}
function finishBattle(){state.over=true;state.phase='over';clearTimeout(autoplayTimer);autoplayTimer=null;log(state.winner==='draw'?'勝負は引き分け！':`${state.winner==='A'?'Aチーム':'Bチーム'}の勝利！`);render();}
function promptReplacement(){const r=state.replacements[state.replacementIndex];if(!r){state.replacements=[];state.turn++;startCommandPhase();return;}state.phase='replacement';state.currentHuman=r.trainer.id;render();cmd.innerHTML='';const h=document.createElement('h3');h.textContent=`${r.trainer.label}：${r.old.name}の交代先を選択`;cmd.appendChild(h);const g=document.createElement('div');g.className='switch-grid';for(const p of r.options.filter(x=>!r.trainer.active.includes(x))){const b=document.createElement('button');b.className='switch-button';b.textContent=`${p.name} HP ${percent(p)}%`;b.onclick=()=>{r.trainer.active[r.slot]=p;p.position=r.old.position;entry(p);log(`${r.trainer.label}は ${p.name}を繰り出した！`);state.replacementIndex++;promptReplacement();};g.appendChild(b);}cmd.appendChild(g);}
function actorList(){return state.trainers.flatMap(t=>t.active.filter(p=>p.hp>0).map(p=>({trainer:t,p})));}
function startCommandPhase(){if(state.over)return;state.phase='command';state.actions=[];state.redirector={A:null,B:null};state.quickGuard={A:false,B:false};state.humanQueue=[];for(const {trainer:t,p} of actorList()){if(p.recharge){state.actions.push({type:'move',actor:p,moveId:p.moves[0]?.id||null,targetUid:null,forced:true});continue;}if(p.charging?.moveId){state.actions.push({type:'move',actor:p,moveId:p.charging.moveId,targetUid:p.charging.targetUid||null,forced:true});continue;}if(t.controller==='cpu')state.actions.push(cpuChoose(p,t));else state.humanQueue.push({trainer:t,p});}state.humanIndex=0;if(!state.humanQueue.length){render();scheduleAutoplay();return;}promptHumanAction();}
function promptHumanAction(){const q=state.humanQueue[state.humanIndex];if(!q){resolveTurn();return;}state.currentHuman=q.trainer.id;render();cmd.innerHTML='';const title=document.createElement('h3');title.textContent=`${q.trainer.label}：${q.p.name} の行動`;cmd.appendChild(title);const mg=document.createElement('div');mg.className='move-grid';for(const m of q.p.moves){const b=document.createElement('button');b.className='move-button';b.disabled=m.pp<=0;b.innerHTML=`<strong>${m.name}</strong><span>${m.type} / ${m.category==='physical'?'物理':m.category==='special'?'特殊':'変化'} / PP ${m.pp}</span>`;b.onclick=()=>chooseHumanMove(q,m);mg.appendChild(b);}cmd.appendChild(mg);const bg=document.createElement('div');bg.className='switch-grid';for(const p of bench(q.trainer)){const b=document.createElement('button');b.className='switch-button';b.textContent=`交代：${p.name} (${percent(p)}%)`;b.onclick=()=>acceptHumanAction({type:'switch',actor:q.p,switchUid:p.uid});bg.appendChild(b);}cmd.appendChild(bg);}
function chooseHumanMove(q,m){let targets=legalTargets(q.p,m);const mode=targetMode(m);if(!['foe','ally'].includes(mode)){acceptHumanAction({type:'move',actor:q.p,moveId:m.id,targetUid:null});return;}cmd.innerHTML='';const h=document.createElement('h3');h.textContent=`${m.name} の対象を選択`;cmd.appendChild(h);const g=document.createElement('div');g.className='switch-grid';for(const p of targets){const b=document.createElement('button');b.className='switch-button';b.textContent=targetLabel(p);b.onclick=()=>acceptHumanAction({type:'move',actor:q.p,moveId:m.id,targetUid:p.uid});g.appendChild(b);}cmd.appendChild(g);}
function acceptHumanAction(a){state.actions.push(a);state.humanIndex++;const next=state.humanQueue[state.humanIndex];if(next&&next.trainer.id!==state.currentHuman){cmd.innerHTML='';const p=document.createElement('div');p.className='pass-card';p.innerHTML=`<h3>端末を ${next.trainer.label} に渡してください</h3><p>前の参加者の入力は確定しました。</p>`;const b=document.createElement('button');b.className='primary-button';b.textContent='続ける';b.onclick=promptHumanAction;p.appendChild(b);cmd.appendChild(p);state.currentHuman=null;renderOperator();return;}promptHumanAction();}
function scheduleAutoplay(force=false){if(state.over||state.humanQueue.length)return;clearTimeout(autoplayTimer);if(state.autoplayPaused&&!force){render();return;}const ms=Number($('format-autoplay-speed')?.value||650);autoplayTimer=setTimeout(()=>resolveTurn(),force?20:ms);}
function renderOperator(){const el=$('format-operator-banner');if(!el||!state)return;el.textContent=state.over?'対戦終了':state.currentHuman?`操作中：${trainerById(state.currentHuman)?.label||state.currentHuman}`:state.phase==='resolving'?'行動解決中':state.trainers.every(t=>t.controller==='cpu')?(state.autoplayPaused?'CPU対戦：一時停止':'CPU対戦：自動進行中'):'入力待ち';}
function renderPokemonCard(p,viewer,enemy){const privateInfo=viewer==='god'||(!enemy&&viewer!=='spectator');const hpText=privateInfo?`${p.hp}/${p.maxHP}`:`${percent(p)}%`;const stage=Object.entries(p.stages).filter(([,v])=>v).map(([k,v])=>`${k[0].toUpperCase()}${v>0?'+':''}${v}`).join(' ')||'変化なし';return `<article class="format-pokemon-card ${p.hp<=0?'fainted':''}"><div class="pokemon-header"><div><h3>${p.name}</h3><span class="type-text">${p.types.join(' / ')}</span></div><span>${p.status?D.STATUS_NAMES?.[p.status]||p.status:''}</span></div><div class="hp-area"><div class="hp-label"><span>HP</span><span>${hpText}</span></div><div class="hp-bar"><div class="hp-fill" style="width:${percent(p)}%"></div></div></div><div class="format-small">${privateInfo?`特性:${p.ability.name} / 持ち物:${activeItem(p)?p.item.name:'なし'} / ${stage}`:`${stage}`}</div></article>`;}
function renderBoard(){if(!state||!board)return;const viewer=state.view;const makeSide=side=>{const wrap=document.createElement('section');wrap.className=`format-side format-side-${side}`;const h=document.createElement('h3');h.textContent=`${side==='A'?'A':'B'}チーム`;wrap.appendChild(h);const grid=document.createElement('div');grid.className=`format-active-grid format-active-${state.format.active}`;for(const {trainer:t,p} of sideSlotEntries(side)){const own=viewer==='god'||viewer===t.id||(viewer==='A'&&side==='A')||(viewer==='B'&&side==='B')||(trainerById(viewer)?.side===side);const div=document.createElement('div');div.className='format-slot';const lab=document.createElement('div');lab.className='format-trainer-label';lab.textContent=t.label;div.appendChild(lab);div.insertAdjacentHTML('beforeend',renderPokemonCard(p,viewer,!own));grid.appendChild(div);}wrap.appendChild(grid);const benchEl=document.createElement('div');benchEl.className='format-bench-line';benchEl.textContent='控え：'+sideTrainers(side).flatMap(t=>bench(t).map(p=>{const own=viewer==='god'||viewer===t.id||(viewer==='A'&&side==='A')||(viewer==='B'&&side==='B')||(viewer&&trainerById(viewer)?.side===side);if(own)return`${t.label}:${p.name} ${p.hp}/${p.maxHP}`;if(!p.seen)return`${t.label}:???`;return`${t.label}:${p.name} ${percent(p)}%`;})).join(' / ');wrap.appendChild(benchEl);return wrap;};board.replaceChildren(makeSide('B'),makeSide('A'));}
function viewerOwnsSide(viewer,side){if(viewer==='god')return true;if(viewer==='A'||viewer==='B')return viewer===side;return trainerById(viewer)?.side===side;}
function formatPokemonContext(p,viewer){const priv=viewerOwnsSide(viewer,p.side);if(!priv&&!p.seen)return'???';const hp=priv?`${p.hp}/${p.maxHP}`:`${percent(p)}%`,bits=[`${p.name} HP ${hp}`];if(p.status)bits.push(`状態:${D.STATUS_NAMES?.[p.status]||p.status}`);const stages=Object.entries(p.stages).filter(([,v])=>v).map(([k,v])=>`${k}:${v>0?'+':''}${v}`);if(stages.length)bits.push(`ランク:${stages.join(',')}`);if(priv){bits.push(`特性:${p.ability.name}`,`持ち物:${p.itemConsumed?'消費済み':p.item.name}`,`技:${p.moves.map(m=>`${m.name}(${m.pp}/${m.maxPP})`).join('/')}`);}else{if(p.abilityRevealed)bits.push(`特性:${p.ability.name}`);if(p.itemRevealed)bits.push(`持ち物:${p.itemConsumed?'消費済み':p.item.name}`);if(p.knownMoves.size)bits.push(`公開技:${[...p.knownMoves].map(id=>mv(id)?.name||id).join('/')}`);}return bits.join(' / ');}
function formatBattleContext(viewer=state?.view){if(!state)return'';const lines=[`【ニワラバトル v${window.NIWARA_APP?.version||''} ${state.format.name} 状況＋ログ】`,`ターン ${state.turn} / 視点 ${viewer}`,`天候:${state.field.weather||'なし'} / フィールド:${state.field.terrain||'なし'} / トリックルーム:${state.field.trickRoom>0?'あり':'なし'}`];for(const side of['A','B']){lines.push('',`■ ${side}チーム`);for(const t of sideTrainers(side)){lines.push(`[${t.label}]`);for(const p of t.active.filter(Boolean))lines.push(`場: ${formatPokemonContext(p,viewer)}`);const bs=bench(t);if(bs.length)lines.push(`控え: ${bs.map(p=>formatPokemonContext(p,viewer)).join(' | ')}`);}}lines.push('','■ ログ',...state.logs.map(x=>`[${x.turn}] ${formatLogText(x,viewer)}`));return lines.join('\n');}
function hasPrivateLogInfo(viewer,meta){if(!meta)return false;if(viewer==='god')return true;if(viewer==='A'||viewer==='B')return meta.targetSide===viewer;const t=trainerById(viewer);return !!t&&t.side===meta.targetSide;}
function formatLogText(e,viewer=state?.view){const m=e.meta;if(!m?.hpChange)return e.text;const exact=hasPrivateLogInfo(viewer,m),amount=exact?String(m.amount):`${Math.max(0,Math.round((m.amount/Math.max(1,m.maxHP))*1000)/10)}%`;return m.hpChange==='heal'?`${m.name}は ${amount} HP ${m.reason||'回復'}した！`:`${m.name}は ${amount} ${m.reason||'ダメージ'}！`;}
function renderLog(){if(!logEl||!state)return;logEl.innerHTML='';for(const e of state.logs.slice(-120)){const d=document.createElement('div');d.className=`log-line ${e.kind||''}`;d.textContent=`[${e.turn}] ${formatLogText(e,state.view)}`;logEl.appendChild(d);}logEl.scrollTop=logEl.scrollHeight;}
function renderViews(){const v=$('format-view-buttons');if(!v||!state)return;v.replaceChildren();const opts=[];for(const t of state.trainers.filter(t=>t.human))opts.push([t.id,`${t.label}視点`]);if(!opts.some(x=>x[0]==='A'))opts.push(['A','Aチーム視点']);if(!opts.some(x=>x[0]==='B'))opts.push(['B','Bチーム視点']);opts.push(['spectator','観戦'],['god','神視点']);for(const [id,label] of opts){const b=document.createElement('button');b.className='ghost-button';b.dataset.active=state.view===id?'true':'false';b.textContent=label;b.onclick=()=>{state.view=id;render();};v.appendChild(b);}}
function render(){if(!state)return;screen.classList.remove('hidden');$('format-battle-title').textContent=`${state.format.name}バトル`;$('format-name-text').textContent=state.format.name;$('format-turn-text').textContent=String(state.turn);$('format-weather-text').textContent=state.field.weather?D.WEATHER_NAMES?.[state.field.weather]||state.field.weather:'なし';$('format-terrain-text').textContent=state.field.terrain||'なし';$('format-room-text').textContent=state.field.trickRoom>0?'トリックルーム':'なし';renderOperator();renderViews();renderBoard();renderLog();const auto=state.trainers.every(t=>t.controller==='cpu');$('format-autoplay-controls')?.classList.toggle('hidden',!auto);if(auto){$('format-autoplay-status').textContent=state.autoplayPaused?'一時停止':'自動進行中';$('format-autoplay-toggle').textContent=state.autoplayPaused?'再開':'一時停止';}if(state.over)cmd.innerHTML=`<div class="notice"><strong>${state.winner==='draw'?'引き分け':`${state.winner}チームの勝利`}</strong></div>`;}
function baseField(){return{weather:null,weatherTurns:0,terrain:null,terrainTurns:0,trickRoom:0,magicRoom:0,tailwind:{A:0,B:0},screens:{A:{reflect:0,lightScreen:0},B:{reflect:0,lightScreen:0}},hazards:{A:{stealthRock:false,spikes:0,stickyWeb:false,toxicSpikes:0},B:{stealthRock:false,spikes:0,stickyWeb:false,toxicSpikes:0}}};}
function setupBattle(format,participants){state={format,trainers:participants,field:baseField(),turn:1,logs:[],actions:[],humanQueue:[],humanIndex:0,currentHuman:null,phase:'start',over:false,winner:null,view:participants.find(t=>t.human)?.id||'spectator',autoplayPaused:false,replacements:[],redirector:{A:null,B:null},quickGuard:{A:false,B:false}};for(const t of participants)activateInitial(t);log(`${format.name}バトルを開始！`);showFormatScreen();startCommandPhase();}
function showFormatScreen(){document.querySelectorAll('section.screen').forEach(s=>s.classList.add('hidden'));screen.classList.remove('hidden');window.scrollTo?.({top:0});render();}
function leaveFormat(){clearTimeout(autoplayTimer);autoplayTimer=null;state=null;screen.classList.add('hidden');$('mode-screen')?.classList.remove('hidden');}
function buildParticipants(format,mode,selectionMap,configs){const arr=[];for(const c of configs){arr.push(trainer(c.id,c.side,c.label,c.controller,c.difficulty,c.roster,selectionMap[c.id]));}return arr;}
function showSelection(format,mode,configs){selectionSession={format,mode,configs,map:{},humanOrder:configs.filter(c=>c.controller==='human').map(c=>c.id),idx:0};for(const c of configs)if(c.controller==='cpu')selectionSession.map[c.id]=cpuSelect(c.roster,format.select,c.difficulty,configs.find(x=>x.side!==c.side)?.roster||[]);showFormatScreen();renderSelectionStep();}
function renderSelectionStep(){const ss=selectionSession;if(!ss)return;const id=ss.humanOrder[ss.idx];if(!id){const parts=buildParticipants(ss.format,ss.mode,ss.map,ss.configs);selectionSession=null;setupBattle(ss.format,parts);return;}const c=ss.configs.find(x=>x.id===id);state={format:ss.format,trainers:[],field:baseField(),turn:0,logs:[],view:id,phase:'selection',currentHuman:id};$('format-battle-title').textContent=`${ss.format.name}：選出`;$('format-battle-subtitle').textContent=`${c.label}：${ss.format.select}匹を順番に選択。最初の${ss.format.id==='tag'?1:ss.format.active}匹が先発です。`;board.innerHTML='';cmd.innerHTML='';const sel=ss.map[id]||[];const count=document.createElement('div');count.className='selection-count';count.textContent=`${sel.length} / ${ss.format.select}`;cmd.appendChild(count);const grid=document.createElement('div');grid.className='preview-grid selectable';c.roster.forEach((set,i)=>{const s=sp(set.speciesId),b=document.createElement('button');b.className='preview-card';const n=sel.indexOf(i);b.innerHTML=`<strong>${n>=0?`${n+1}. `:''}${s.name}</strong><span>${s.types.join(' / ')}</span>`;b.onclick=()=>{const cur=ss.map[id]||[];const at=cur.indexOf(i);if(at>=0)cur.splice(at,1);else if(cur.length<ss.format.select)cur.push(i);ss.map[id]=cur;renderSelectionStep();};grid.appendChild(b);});cmd.appendChild(grid);const ok=document.createElement('button');ok.className='primary-button';ok.disabled=sel.length!==ss.format.select;ok.textContent='選出を確定';ok.onclick=()=>{ss.idx++;if(ss.idx<ss.humanOrder.length){cmd.innerHTML='';const p=document.createElement('div');p.className='pass-card';p.innerHTML=`<h3>端末を次のプレイヤーへ渡してください</h3><p>${c.label}の選出を確定しました。</p>`;const nx=document.createElement('button');nx.className='primary-button';nx.textContent='続ける';nx.onclick=renderSelectionStep;p.appendChild(nx);cmd.appendChild(p);}else renderSelectionStep();};cmd.appendChild(ok);renderOperator();}
function nonTagConfigs(mode){const aSource=$('player-a-party-source')?.value||'current',bSource=$('player-b-party-source')?.value||'random';return[{id:'A1',side:'A',label:mode==='cpu-cpu'?'CPU A':'プレイヤーA',controller:mode==='cpu-cpu'?'cpu':'human',difficulty:$('cpu-difficulty-a-select')?.value||'very-strong',roster:resolveSource(aSource)},{id:'B1',side:'B',label:mode==='pvp'?'プレイヤーB':'CPU B',controller:mode==='pvp'?'human':'cpu',difficulty:$('cpu-difficulty-b-select')?.value||'very-strong',roster:resolveSource(bSource)}];}
function renderTagConfig(){
  const host=$('tag-participant-config');if(!host)return;const tag=fmtSelect.value==='tag';host.classList.toggle('hidden',!tag);if(!tag)return;
  const prev={};for(const id of ['A1','A2','B1','B2'])prev[id]={controller:document.querySelector(`[data-tag-controller="${id}"]`)?.value,source:document.querySelector(`[data-tag-source="${id}"]`)?.value,diff:document.querySelector(`[data-tag-diff="${id}"]`)?.value};
  host.replaceChildren();const h=document.createElement('h3');h.textContent='タッグ参加者（A1＋A2 vs B1＋B2）';host.appendChild(h);const note=document.createElement('p');note.className='view-note';note.textContent='4人それぞれを人間/CPUから自由に選べます。各参加者は6匹から3匹を選び、1匹ずつ場に出します。';host.appendChild(note);const grid=document.createElement('div');grid.className='tag-config-grid';host.appendChild(grid);
  const sources=sourceOptions();for(const [i,id] of ['A1','A2','B1','B2'].entries()){
    const card=document.createElement('div');card.className='tag-config-card';const strong=document.createElement('strong');strong.textContent=id;card.appendChild(strong);
    const controller=document.createElement('select');controller.dataset.tagController=id;[['human','プレイヤー'],['cpu','CPU']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;controller.appendChild(o);});controller.value=prev[id].controller|| (i===0?'human':'cpu');const cl=document.createElement('label');cl.append('操作',controller);card.appendChild(cl);
    const source=document.createElement('select');source.dataset.tagSource=id;for(const x of sources){const o=document.createElement('option');o.value=x.value;o.textContent=x.text;source.appendChild(o);}if(prev[id].source&&[...source.options].some(o=>o.value===prev[id].source))source.value=prev[id].source;const sl=document.createElement('label');sl.append('パーティー',source);card.appendChild(sl);
    const diff=document.createElement('select');diff.dataset.tagDiff=id;[['normal','普通'],['strong','強い'],['very-strong','非常に強い']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;diff.appendChild(o);});diff.value=prev[id].diff||'very-strong';const dl=document.createElement('label');dl.append('CPU強度',diff);card.appendChild(dl);
    grid.appendChild(card);
  }
}

function applyTagModePreset(){if(fmtSelect.value!=='tag')return;renderTagConfig();const mode=modeSelect.value;const map=mode==='cpu-cpu'?{A1:'cpu',A2:'cpu',B1:'cpu',B2:'cpu'}:mode==='pvp'?{A1:'human',A2:'cpu',B1:'human',B2:'cpu'}:{A1:'human',A2:'cpu',B1:'cpu',B2:'cpu'};for(const[id,v]of Object.entries(map)){const el=document.querySelector(`[data-tag-controller="${id}"]`);if(el)el.value=v;}}
function tagConfigs(){return['A1','A2','B1','B2'].map(id=>{const side=id[0],controller=document.querySelector(`[data-tag-controller="${id}"]`)?.value||'cpu',source=document.querySelector(`[data-tag-source="${id}"]`)?.value||'current',difficulty=document.querySelector(`[data-tag-diff="${id}"]`)?.value||'very-strong';return{id,side,label:controller==='cpu'?`CPU ${id}`:`プレイヤー ${id}`,controller,difficulty,roster:resolveSource(source)};});}
function startFromMode(){const fid=fmtSelect.value;if(fid==='single')return false;const format=FORMATS[fid];if(!format)return false;const mode=modeSelect.value;if(fid==='tag')renderTagConfig();const configs=fid==='tag'?tagConfigs():nonTagConfigs(mode);for(const c of configs){if(!Array.isArray(c.roster)||c.roster.length!==6){alert(`${c.label}の6匹パーティーを準備してください。`);return true;}}showSelection(format,mode,configs);return true;}
continueBtn.addEventListener('click',e=>{if(startFromMode()){e.preventDefault();e.stopImmediatePropagation();}},true);
fmtSelect.addEventListener('change',()=>{renderTagConfig();if(fmtSelect.value==='tag')applyTagModePreset();const single=fmtSelect.value==='single';$('mode-help-note').textContent=single?'シングルは従来エンジンを使用します。':fmtSelect.value==='tag'?'タッグは4人を個別にプレイヤー/CPUへ変更できます。対戦モードの選択は初期配置のプリセットとして使われます。':'ダブル/トリプル/6vs6はv12フォーマットエンジンを使用します。CPU戦・対人・CPU同士に対応します。';});
modeSelect.addEventListener('change',()=>{if(fmtSelect.value==='tag')applyTagModePreset();});
$('format-battle-exit')?.addEventListener('click',leaveFormat);
$('format-autoplay-toggle')?.addEventListener('click',()=>{if(!state)return;state.autoplayPaused=!state.autoplayPaused;if(!state.autoplayPaused)scheduleAutoplay();render();});
$('format-autoplay-step')?.addEventListener('click',()=>{if(state&&!state.over&&state.trainers.every(t=>t.controller==='cpu'))scheduleAutoplay(true);});
$('format-autoplay-speed')?.addEventListener('change',()=>{if(state&&!state.autoplayPaused&&state.trainers.every(t=>t.controller==='cpu'))scheduleAutoplay();});
$('format-pokedex-button')?.addEventListener('click',()=>$('open-pokedex-button')?.click());
$('format-copy-log-button')?.addEventListener('click',async()=>{if(!state)return;const txt=formatBattleContext(state.view);try{await navigator.clipboard.writeText(txt);log('状況＋ログをコピーしました。');}catch(_){prompt('コピーしてください',txt);}});
renderTagConfig();
window.NIWARA_FORMATS=Object.freeze({FORMATS,get state(){return state;},startFromMode,targetMode,FORMAT_LABEL});
})();
