/* ニワラバトル v11 environment research UI / worker manager */
(function(){
  'use strict';
  const VERSION = window.NIWARA_APP?.version || '11.0.0';
  const DB_NAME='niwaraBattleResearchV11', STORE='runs', DB_VERSION=1;
  const $=id=>document.getElementById(id);
  const openBtn=$('open-research-button'), screen=$('research-screen'), closeBtn=$('research-close-button');
  if(!openBtn||!screen)return;
  let previousScreen=null,currentRun=null,workers=[],pending=new Map(),paused=true,lastRateAt=0,lastRateCompleted=0,renderTimer=null,saveChain=Promise.resolve();
  const speciesName=id=>window.NIWARA_DATA?.SPECIES_DEX?.[id]?.name||id;
  const moveName=id=>window.NIWARA_DATA?.MOVE_DEX?.[id]?.name||id;
  const itemName=id=>window.NIWARA_DATA?.ITEM_DEX?.[id]?.name||id;
  const abilityName=id=>{for(const sp of Object.values(window.NIWARA_DATA?.SPECIES_DEX||{})){const a=sp.abilities?.find(x=>x.id===id);if(a)return a.name;}return id;};
  function emptyStats(){return{battles:0,wins:{A:0,B:0,draw:0},turns:0,switches:0,species:{},moves:{},abilities:{},items:{},spreads:{},matchups:{}};}
  function mergeStats(a,b){a=a||emptyStats();if(!b)return a;a.battles+=(b.battles||0);a.turns+=(b.turns||0);a.switches+=(b.switches||0);for(const k of ['A','B','draw'])a.wins[k]=(a.wins[k]||0)+(b.wins?.[k]||0);for(const key of ['abilities','items','spreads'])for(const [k,v] of Object.entries(b[key]||{}))a[key][k]=(a[key][k]||0)+v;for(const [k,v] of Object.entries(b.species||{})){const t=a.species[k]||(a.species[k]={roster:0,selected:0,leads:0,teamWins:0,selectedWins:0,leadWins:0,kos:0,deaths:0});for(const x of Object.keys(t))t[x]+=(v[x]||0);}for(const [k,v] of Object.entries(b.moves||{})){const t=a.moves[k]||(a.moves[k]={uses:0,hits:0,damage:0,kos:0});for(const x of Object.keys(t))t[x]+=(v[x]||0);}for(const [k,v] of Object.entries(b.matchups||{})){const t=a.matchups[k]||(a.matchups[k]={games:0,wins:0});t.games+=v.games||0;t.wins+=v.wins||0;}return a;}
  function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
  async function dbPut(run){const db=await dbOpen();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(run);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
  async function dbAll(){const db=await dbOpen();const rows=await new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);});db.close();return rows.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));}
  async function dbDelete(id){const db=await dbOpen();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
  function cloneForStore(value){try{return structuredClone(value);}catch(_){return JSON.parse(JSON.stringify(value));}}
  function saveRun(run){const snapshot=cloneForStore(run);saveChain=saveChain.catch(()=>{}).then(()=>dbPut(snapshot));return saveChain;}
  function uid(){return `sim-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;}
  function num(id,def=0){const n=Number($(id)?.value);return Number.isFinite(n)?n:def;}
  function configFromUI(){return{name:($('research-run-name')?.value||'').trim()||`環境研究 ${new Date().toLocaleString('ja-JP')}`,target:clamp(num('research-target',10000),1,1000000),difficultyA:$('research-ai-a')?.value||'very-strong',difficultyB:$('research-ai-b')?.value||'very-strong',buildMode:$('research-build-mode')?.value||'auto',workers:clamp(num('research-workers',Math.min(4,navigator.hardwareConcurrency||2)),1,8),seed:($('research-seed')?.value||'niwara-v11').trim()||'niwara-v11',turnLimit:clamp(num('research-turn-limit',200),20,500)};}
  function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
  function makeRun(config){return{id:uid(),version:VERSION,name:config.name,createdAt:Date.now(),updatedAt:Date.now(),status:'paused',config:{difficultyA:config.difficultyA,difficultyB:config.difficultyB,buildMode:config.buildMode,seed:config.seed,turnLimit:config.turnLimit},target:config.target,workers:config.workers,completed:0,queueCursor:0,todoRanges:[],inflight:[],stats:emptyStats()};}
  function batchSize(run){if(run.target<=2000)return 10;if(run.target<=10000)return 25;if(run.target<=50000)return 50;return 100;}
  function nextRange(run){if(run.todoRanges?.length)return run.todoRanges.shift();if(run.queueCursor>=run.target)return null;const start=run.queueCursor,count=Math.min(batchSize(run),run.target-start);run.queueCursor+=count;return{start,count};}
  function setStatus(text,kind=''){const el=$('research-status');if(!el)return;el.textContent=text;el.dataset.kind=kind;}
  function stopWorkers({requeue=true}={}){for(const w of workers)w.terminate();workers=[];if(requeue&&currentRun){for(const p of pending.values())currentRun.todoRanges.push({start:p.start,count:p.count});currentRun.inflight=[];}pending.clear();}
  async function pause(){if(!currentRun)return;paused=true;stopWorkers({requeue:true});currentRun.status=currentRun.completed>=currentRun.target?'complete':'paused';currentRun.updatedAt=Date.now();await saveRun(currentRun);setStatus(currentRun.status==='complete'?'完了':'一時停止中');renderAll();await renderHistory();}
  function makeWorker(index){const w=new Worker('sim-worker.js');w.__index=index;w.onmessage=ev=>onWorkerMessage(w,ev.data||{});w.onerror=e=>{console.error('research worker',e);setStatus(`Worker ${index+1} エラー`,'error');};return w;}
  async function startRun(run){if(currentRun&&currentRun.id!==run.id)stopWorkers({requeue:true});currentRun=run;paused=false;run.status='running';run.updatedAt=Date.now();if(Array.isArray(run.inflight)&&run.inflight.length){run.todoRanges.push(...run.inflight);run.inflight=[];}workers=Array.from({length:clamp(run.workers||2,1,8)},(_,i)=>makeWorker(i));lastRateAt=performance.now();lastRateCompleted=run.completed;await saveRun(run);setStatus('計算中');workers.forEach(dispatch);renderAll();}
  function dispatch(w){if(paused||!currentRun)return;if(currentRun.completed>=currentRun.target){finish();return;}const range=nextRange(currentRun);if(!range){if(pending.size===0)finish();return;}const id=`${currentRun.id}:${range.start}:${range.count}`;pending.set(id,{...range,worker:w.__index});currentRun.inflight=[...pending.values()].map(({start,count})=>({start,count}));w.postMessage({type:'run',id,start:range.start,count:range.count,config:{...currentRun.config,seed:currentRun.config.seed}});}
  async function onWorkerMessage(w,msg){if(!currentRun||msg.type==='error'){if(msg.type==='error'){console.error(msg.error);setStatus('シミュレーション中にエラーが発生しました','error');await pause();}return;}const p=pending.get(msg.id);if(!p)return;pending.delete(msg.id);currentRun.inflight=[...pending.values()].map(({start,count})=>({start,count}));mergeStats(currentRun.stats,msg.stats);currentRun.completed+=msg.count||p.count;currentRun.updatedAt=Date.now();await saveRun(currentRun);renderAll();if(currentRun.completed>=currentRun.target&&pending.size===0){finish();return;}dispatch(w);}
  async function finish(){if(!currentRun)return;paused=true;stopWorkers({requeue:false});currentRun.status='complete';currentRun.completed=Math.min(currentRun.completed,currentRun.target);currentRun.updatedAt=Date.now();await saveRun(currentRun);setStatus('完了','complete');renderAll();await renderHistory();}
  function pct(n,d,digits=1){return d?`${(n*100/d).toFixed(digits)}%`:'-';}
  function fmt(n){return Number(n||0).toLocaleString('ja-JP');}
  function rateNow(){if(!currentRun)return 0;const now=performance.now(),dt=(now-lastRateAt)/1000;if(dt>=1){const r=(currentRun.completed-lastRateCompleted)/dt;currentRun.__rate=r;lastRateAt=now;lastRateCompleted=currentRun.completed;}return currentRun.__rate||0;}
  function renderProgress(){const r=currentRun;const bar=$('research-progress-bar'),text=$('research-progress-text'),meta=$('research-progress-meta');if(!r){if(bar)bar.style.width='0%';if(text)text.textContent='未開始';if(meta)meta.textContent='';if(openBtn)openBtn.textContent='環境研究';return;}const p=r.target?Math.min(100,r.completed*100/r.target):0;if(bar)bar.style.width=`${p}%`;if(text)text.textContent=`${fmt(r.completed)} / ${fmt(r.target)} 試合（${p.toFixed(1)}%）`;if(openBtn)openBtn.textContent=r.status==='running'?`環境研究 ${p.toFixed(0)}%`:'環境研究';const rate=rateNow();if(meta)meta.textContent=`${r.name}｜${r.status==='complete'?'完了':r.status==='running'?'計算中':'一時停止'}${rate?`｜約 ${rate.toFixed(1)} 試合/秒`:''}`;}
  function tableRowsSpecies(stats){const b=Math.max(1,stats.battles*2);return Object.entries(stats.species||{}).map(([id,s])=>({id,name:speciesName(id),usage:s.roster/b,select:s.selected/Math.max(1,s.roster),lead:s.leads/Math.max(1,s.selected),win:s.selectedWins/Math.max(1,s.selected),teamWin:s.teamWins/Math.max(1,s.roster),kos:s.kos,deaths:s.deaths})).sort((a,b)=>b.usage-a.usage);}
  function renderSpecies(stats){const body=$('research-species-body');if(!body)return;body.replaceChildren();for(const r of tableRowsSpecies(stats).slice(0,100)){const tr=document.createElement('tr');for(const v of [r.name,pct(r.usage,1),pct(r.select,1),pct(r.lead,1),pct(r.win,1),fmt(r.kos),fmt(r.deaths)]){const td=document.createElement('td');td.textContent=v;tr.appendChild(td);}body.appendChild(tr);}}
  function renderMoves(stats){const body=$('research-moves-body');if(!body)return;body.replaceChildren();const rows=Object.entries(stats.moves||{}).map(([id,s])=>({id,name:moveName(id),...s})).sort((a,b)=>b.uses-a.uses).slice(0,100);for(const r of rows){const tr=document.createElement('tr');for(const v of [r.name,fmt(r.uses),pct(r.hits,r.uses),r.hits?(r.damage/r.hits).toFixed(1):'-',fmt(r.kos)]){const td=document.createElement('td');td.textContent=v;tr.appendChild(td);}body.appendChild(tr);}}
  function renderSimpleMap(id,map,nameFn,total){const body=$(id);if(!body)return;body.replaceChildren();for(const [key,count] of Object.entries(map||{}).sort((a,b)=>b[1]-a[1]).slice(0,100)){const tr=document.createElement('tr');const a=document.createElement('td'),b=document.createElement('td'),c=document.createElement('td');a.textContent=nameFn(key);b.textContent=fmt(count);c.textContent=pct(count,total);tr.append(a,b,c);body.appendChild(tr);}}
  function renderSpreads(stats){const body=$('research-spreads-body');if(!body)return;body.replaceChildren();const rows=Object.entries(stats.spreads||{}).map(([key,count])=>{const [id,nature,spread]=key.split('|');return{id,nature,spread,count};}).sort((a,b)=>b.count-a.count).slice(0,100);for(const r of rows){const tr=document.createElement('tr');for(const v of [speciesName(r.id),r.nature,r.spread,fmt(r.count)]){const td=document.createElement('td');td.textContent=v;tr.appendChild(td);}body.appendChild(tr);}}
  function renderMatchups(stats){const body=$('research-matchups-body');if(!body)return;body.replaceChildren();const rows=Object.entries(stats.matchups||{}).filter(([,v])=>v.games>=Math.max(5,stats.battles*0.001)).map(([k,v])=>{const[a,b]=k.split('>');return{a,b,games:v.games,win:v.wins/Math.max(1,v.games)};}).sort((a,b)=>b.games-a.games).slice(0,100);for(const r of rows){const tr=document.createElement('tr');for(const v of [`${speciesName(r.a)} → ${speciesName(r.b)}`,fmt(r.games),pct(r.win,1)]){const td=document.createElement('td');td.textContent=v;tr.appendChild(td);}body.appendChild(tr);}}
  function renderSummary(stats){const el=$('research-summary');if(!el)return;const b=stats.battles||0;el.innerHTML='';const values=[['試合数',fmt(b)],['平均ターン',b?(stats.turns/b).toFixed(1):'-'],['平均交代回数',b?(stats.switches/b).toFixed(1):'-'],['A勝率',pct(stats.wins?.A||0,b)],['B勝率',pct(stats.wins?.B||0,b)],['引き分け',pct(stats.wins?.draw||0,b)]];for(const [k,v] of values){const card=document.createElement('div');card.className='research-kpi';const s=document.createElement('span'),strong=document.createElement('strong');s.textContent=k;strong.textContent=v;card.append(s,strong);el.appendChild(card);}}
  function renderAll(){renderProgress();const s=currentRun?.stats||emptyStats();renderSummary(s);renderSpecies(s);renderMoves(s);renderSpreads(s);renderSimpleMap('research-items-body',s.items,itemName,Math.max(1,s.battles*12));renderSimpleMap('research-abilities-body',s.abilities,abilityName,Math.max(1,s.battles*12));renderMatchups(s);if($('research-pause'))$('research-pause').disabled=!currentRun||currentRun.status!=='running';if($('research-resume'))$('research-resume').disabled=!currentRun||currentRun.status==='running'||currentRun.completed>=currentRun.target;}
  async function renderHistory(){const runs=await dbAll();const body=$('research-history-body');if(body){body.replaceChildren();for(const r of runs.slice(0,30)){const tr=document.createElement('tr');const meta=[r.name,`v${r.version||'?'}`,`${fmt(r.completed)}/${fmt(r.target)}`,r.status==='complete'?'完了':'途中',new Date(r.updatedAt).toLocaleString('ja-JP')];for(const v of meta){const td=document.createElement('td');td.textContent=v;tr.appendChild(td);}const act=document.createElement('td');const load=document.createElement('button');load.className='ghost-button compact-button';load.textContent='表示';load.onclick=()=>loadRun(r.id);act.appendChild(load);if(r.completed<r.target){const resume=document.createElement('button');resume.className='ghost-button compact-button';resume.textContent='再開';resume.onclick=async()=>{await loadRun(r.id);startRun(currentRun);};act.appendChild(resume);}const del=document.createElement('button');del.className='ghost-button compact-button danger-text';del.textContent='削除';del.onclick=async()=>{if(confirm(`「${r.name}」を削除しますか？`)){if(currentRun?.id===r.id){stopWorkers({requeue:false});currentRun=null;}await dbDelete(r.id);renderAll();renderHistory();}};act.appendChild(del);tr.appendChild(act);body.appendChild(tr);}}
    for(const id of ['research-compare-base','research-compare-new']){const sel=$(id);if(!sel)continue;const old=sel.value;sel.replaceChildren();for(const r of runs){const o=document.createElement('option');o.value=r.id;o.textContent=`${r.name} (${fmt(r.completed)})`;sel.appendChild(o);}if(runs.some(x=>x.id===old))sel.value=old;} }
  async function loadRun(id){const runs=await dbAll();const r=runs.find(x=>x.id===id);if(!r)return;if(r.status==='running'){r.status='paused';if(r.inflight?.length){r.todoRanges=(r.todoRanges||[]).concat(r.inflight);r.inflight=[];}await saveRun(r);}currentRun=r;paused=true;stopWorkers({requeue:false});if($('research-run-name'))$('research-run-name').value=r.name||'';if($('research-target'))$('research-target').value=r.target||10000;if($('research-ai-a'))$('research-ai-a').value=r.config?.difficultyA||'very-strong';if($('research-ai-b'))$('research-ai-b').value=r.config?.difficultyB||'very-strong';if($('research-build-mode'))$('research-build-mode').value=r.config?.buildMode||'auto';if($('research-seed'))$('research-seed').value=r.config?.seed||'niwara-v11';if($('research-turn-limit'))$('research-turn-limit').value=r.config?.turnLimit||200;if($('research-workers'))$('research-workers').value=String(r.workers||Math.min(4,navigator.hardwareConcurrency||2));setStatus(r.status==='complete'?'完了':'保存済み結果を表示');renderAll();}
  function download(name,text,type){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function exportJson(){if(!currentRun)return;download(`${safeName(currentRun.name)}.json`,JSON.stringify(currentRun,null,2),'application/json');}
  function exportCsv(){if(!currentRun)return;const s=currentRun.stats,lines=['section,name,metric1,metric2,metric3,metric4'];for(const r of tableRowsSpecies(s))lines.push(['species',r.name,(r.usage*100).toFixed(3),(r.select*100).toFixed(3),(r.win*100).toFixed(3),r.kos].map(csv).join(','));for(const [id,m] of Object.entries(s.moves||{}))lines.push(['move',moveName(id),m.uses,m.hits,m.damage,m.kos].map(csv).join(','));for(const [id,c] of Object.entries(s.items||{}))lines.push(['item',itemName(id),c,'','',''].map(csv).join(','));for(const [id,c] of Object.entries(s.abilities||{}))lines.push(['ability',abilityName(id),c,'','',''].map(csv).join(','));download(`${safeName(currentRun.name)}.csv`,lines.join('\n'),'text/csv;charset=utf-8');}
  function csv(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
  function safeName(s){return String(s||'niwara-research').replace(/[\\/:*?"<>|]/g,'_');}
  async function compareRuns(){const ids=[$('research-compare-base')?.value,$('research-compare-new')?.value];const runs=await dbAll();const a=runs.find(r=>r.id===ids[0]),b=runs.find(r=>r.id===ids[1]);const body=$('research-compare-body');if(!body)return;body.replaceChildren();if(!a||!b)return;const ar=Object.fromEntries(tableRowsSpecies(a.stats).map(x=>[x.id,x])),br=Object.fromEntries(tableRowsSpecies(b.stats).map(x=>[x.id,x]));const idsAll=[...new Set([...Object.keys(ar),...Object.keys(br)])];const rows=idsAll.map(id=>({id,name:speciesName(id),usageA:ar[id]?.usage||0,usageB:br[id]?.usage||0,winA:ar[id]?.win||0,winB:br[id]?.win||0})).sort((x,y)=>Math.abs(y.usageB-y.usageA)-Math.abs(x.usageB-x.usageA));for(const r of rows){const tr=document.createElement('tr');for(const v of [r.name,pct(r.usageA,1),pct(r.usageB,1),`${((r.usageB-r.usageA)*100).toFixed(1)}pt`,pct(r.winA,1),pct(r.winB,1),`${((r.winB-r.winA)*100).toFixed(1)}pt`]){const td=document.createElement('td');td.textContent=v;tr.appendChild(td);}body.appendChild(tr);}}
  async function clearAll(){paused=true;stopWorkers({requeue:false});currentRun=null;try{await saveChain;}catch(_){}await new Promise(resolve=>{const req=indexedDB.deleteDatabase(DB_NAME);req.onsuccess=req.onerror=req.onblocked=()=>resolve();});saveChain=Promise.resolve();renderAll();await renderHistory();setStatus('環境研究データを初期化しました');}
  function openResearch(){previousScreen=[...document.querySelectorAll('section.screen')].find(s=>!s.classList.contains('hidden')&&s!==screen)||$('builder-screen');document.querySelectorAll('section.screen').forEach(s=>s.classList.add('hidden'));screen.classList.remove('hidden');renderAll();renderHistory();}
  function closeResearch(){screen.classList.add('hidden');(previousScreen||$('builder-screen'))?.classList.remove('hidden');}
  openBtn.addEventListener('click',openResearch);closeBtn?.addEventListener('click',closeResearch);
  $('research-start')?.addEventListener('click',async()=>{const c=configFromUI();const r=makeRun(c);currentRun=r;await startRun(r);});
  $('research-pause')?.addEventListener('click',pause);$('research-resume')?.addEventListener('click',()=>currentRun&&startRun(currentRun));
  $('research-export-json')?.addEventListener('click',exportJson);$('research-export-csv')?.addEventListener('click',exportCsv);$('research-compare-button')?.addEventListener('click',compareRuns);
  document.querySelectorAll('[data-research-target]').forEach(b=>b.addEventListener('click',()=>{$('research-target').value=b.dataset.researchTarget;}));
  const workerSelect=$('research-workers');if(workerSelect){const n=String(Math.min(4,navigator.hardwareConcurrency||2));if([...workerSelect.options].some(o=>o.value===n))workerSelect.value=n;}
  setInterval(()=>{if(currentRun?.status==='running')renderProgress();},1000);
  window.addEventListener('pagehide',()=>{if(currentRun?.status==='running'){for(const p of pending.values())currentRun.todoRanges.push({start:p.start,count:p.count});currentRun.inflight=[];currentRun.status='paused';currentRun.updatedAt=Date.now();saveRun(currentRun).catch(()=>{});}stopWorkers({requeue:false});});
  renderAll();renderHistory().catch(console.warn);
  window.NIWARA_RESEARCH=Object.freeze({version:VERSION,get currentRun(){return currentRun;},pause,start:()=>currentRun&&startRun(currentRun),clearAll});
})();
