/* ニワラバトル v12 environment research UI / worker manager */
(function(){
'use strict';
const VERSION=window.NIWARA_APP?.version||'12.0.0';
const DB_NAME='niwaraBattleResearchV11',STORE='runs',DB_VERSION=2;
const $=id=>document.getElementById(id),openBtn=$('open-research-button'),screen=$('research-screen'),closeBtn=$('research-close-button');
if(!openBtn||!screen)return;
let previousScreen=null,currentRun=null,workers=[],pending=new Map(),paused=true,lastRateAt=0,lastRateCompleted=0,saveChain=Promise.resolve();
const DATA=window.NIWARA_DATA||{},speciesName=id=>DATA.SPECIES_DEX?.[id]?.name||id,moveName=id=>DATA.MOVE_DEX?.[id]?.name||id,itemName=id=>DATA.ITEM_DEX?.[id]?.name||id;
const FORMAT_NAME={single:'シングル',double:'ダブル',triple:'トリプル',full6:'6vs6',tag:'タッグ'};
function abilityName(id){for(const sp of Object.values(DATA.SPECIES_DEX||{})){const a=sp.abilities?.find(x=>x.id===id);if(a)return a.name;}return id;}
function newSpecies(){return{roster:0,selected:0,leads:0,teamWins:0,selectedWins:0,leadWins:0,kos:0,deaths:0,moves:{},moveSets:{},abilities:{},items:{},spreads:{},matchups:{}};}
function emptyStats(format='single'){return{format,battles:0,wins:{A:0,B:0,draw:0},turns:0,switches:0,species:{},moves:{},abilities:{},items:{},spreads:{},matchups:{},encounters:{}};}
function addMap(a,b){for(const[k,v]of Object.entries(b||{}))a[k]=(a[k]||0)+v;}
function mergeStats(a,b){a=a||emptyStats(b?.format);if(!b)return a;a.format=b.format||a.format;a.battles+=b.battles||0;a.turns+=b.turns||0;a.switches+=b.switches||0;for(const k of['A','B','draw'])a.wins[k]=(a.wins[k]||0)+(b.wins?.[k]||0);for(const k of['abilities','items','spreads'])addMap(a[k],b[k]);for(const[id,v]of Object.entries(b.species||{})){const t=a.species[id]||(a.species[id]=newSpecies());for(const k of['roster','selected','leads','teamWins','selectedWins','leadWins','kos','deaths'])t[k]+=(v[k]||0);addMap(t.abilities,v.abilities);addMap(t.items,v.items);addMap(t.spreads,v.spreads);addMap(t.moveSets,v.moveSets);for(const[mid,m]of Object.entries(v.moves||{})){const x=t.moves[mid]||(t.moves[mid]={uses:0,hits:0,damage:0,kos:0});for(const k of['uses','hits','damage','kos'])x[k]+=(m[k]||0);}for(const[oid,m]of Object.entries(v.matchups||{})){const x=t.matchups[oid]||(t.matchups[oid]={games:0,wins:0,losses:0,kos:0,deaths:0});for(const k of['games','wins','losses','kos','deaths'])x[k]+=(m[k]||0);}}
for(const[id,v]of Object.entries(b.moves||{})){const t=a.moves[id]||(a.moves[id]={uses:0,hits:0,damage:0,kos:0});for(const k of['uses','hits','damage','kos'])t[k]+=(v[k]||0);}for(const[id,v]of Object.entries(b.matchups||{})){const t=a.matchups[id]||(a.matchups[id]={games:0,wins:0});t.games+=v.games||0;t.wins+=v.wins||0;}for(const[id,v]of Object.entries(b.encounters||{})){const t=a.encounters[id]||(a.encounters[id]={games:0,wins:0,losses:0,kos:0,deaths:0});for(const k of['games','wins','losses','kos','deaths'])t[k]+=(v[k]||0);}return a;}
function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function dbPut(run){const db=await dbOpen();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(run);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});db.close();}
async function dbAll(){const db=await dbOpen();const rows=await new Promise((res,rej)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});db.close();return rows.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));}
async function dbDelete(id){const db=await dbOpen();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});db.close();}
function clone(v){try{return structuredClone(v);}catch(_){return JSON.parse(JSON.stringify(v));}}
function saveRun(r){const snap=clone(r);saveChain=saveChain.catch(()=>{}).then(()=>dbPut(snap));return saveChain;}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const num=(id,d=0)=>{const n=Number($(id)?.value);return Number.isFinite(n)?n:d;};const fmt=n=>Number(n||0).toLocaleString('ja-JP');const pct=(n,d,dig=1)=>d?`${(n*100/d).toFixed(dig)}%`:'-';
function configFromUI(){return{name:($('research-run-name')?.value||'').trim()||`環境研究 ${new Date().toLocaleString('ja-JP')}`,format:$('research-format')?.value||'single',target:clamp(num('research-target',10000),1,1000000),difficultyA:$('research-ai-a')?.value||'very-strong',difficultyB:$('research-ai-b')?.value||'very-strong',buildMode:$('research-build-mode')?.value||'auto',workers:clamp(num('research-workers',Math.min(4,navigator.hardwareConcurrency||2)),1,8),seed:($('research-seed')?.value||'niwara-v12').trim()||'niwara-v12',turnLimit:clamp(num('research-turn-limit',200),20,500)};}
function uid(){return`sim-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;}
function makeRun(c){return{id:uid(),version:VERSION,name:c.name,createdAt:Date.now(),updatedAt:Date.now(),status:'paused',config:{format:c.format,difficultyA:c.difficultyA,difficultyB:c.difficultyB,buildMode:c.buildMode,seed:c.seed,turnLimit:c.turnLimit},target:c.target,workers:c.workers,completed:0,queueCursor:0,todoRanges:[],inflight:[],stats:emptyStats(c.format)};}
function batchSize(r){if(r.target<=2000)return 8;if(r.target<=10000)return 20;if(r.target<=50000)return 40;return 80;}
function nextRange(r){if(r.todoRanges?.length)return r.todoRanges.shift();if(r.queueCursor>=r.target)return null;const start=r.queueCursor,count=Math.min(batchSize(r),r.target-start);r.queueCursor+=count;return{start,count};}
function setStatus(t,k=''){const e=$('research-status');if(e){e.textContent=t;e.dataset.kind=k;}}
function stopWorkers({requeue=true}={}){for(const w of workers)w.terminate();workers=[];if(requeue&&currentRun){for(const p of pending.values())currentRun.todoRanges.push({start:p.start,count:p.count});currentRun.inflight=[];}pending.clear();}
async function pause(){if(!currentRun)return;paused=true;stopWorkers({requeue:true});currentRun.status=currentRun.completed>=currentRun.target?'complete':'paused';currentRun.updatedAt=Date.now();await saveRun(currentRun);setStatus(currentRun.status==='complete'?'完了':'一時停止中');renderAll();await renderHistory();}
function makeWorker(i){const w=new Worker('sim-worker.js');w.__index=i;w.onmessage=e=>onWorkerMessage(w,e.data||{});w.onerror=e=>{console.error(e);setStatus(`Worker ${i+1} エラー`,'error');};return w;}
async function startRun(run){if(currentRun&&currentRun.id!==run.id)stopWorkers({requeue:true});currentRun=run;paused=false;run.status='running';run.updatedAt=Date.now();run.config.format=run.config.format||'single';run.stats.format=run.config.format;if(run.inflight?.length){run.todoRanges.push(...run.inflight);run.inflight=[];}workers=Array.from({length:clamp(run.workers||2,1,8)},(_,i)=>makeWorker(i));lastRateAt=performance.now();lastRateCompleted=run.completed;await saveRun(run);setStatus('計算中');workers.forEach(dispatch);renderAll();}
function dispatch(w){if(paused||!currentRun)return;if(currentRun.completed>=currentRun.target){finish();return;}const r=nextRange(currentRun);if(!r){if(!pending.size)finish();return;}const id=`${currentRun.id}:${r.start}:${r.count}`;pending.set(id,{...r,worker:w.__index});currentRun.inflight=[...pending.values()].map(({start,count})=>({start,count}));w.postMessage({type:'run',id,start:r.start,count:r.count,config:{...currentRun.config}});}
async function onWorkerMessage(w,m){if(!currentRun)return;if(m.type==='error'){console.error(m.error);setStatus('シミュレーション中にエラー','error');await pause();return;}const p=pending.get(m.id);if(!p)return;pending.delete(m.id);currentRun.inflight=[...pending.values()].map(({start,count})=>({start,count}));mergeStats(currentRun.stats,m.stats);currentRun.completed+=m.count||p.count;currentRun.updatedAt=Date.now();await saveRun(currentRun);renderAll();if(currentRun.completed>=currentRun.target&&!pending.size){finish();return;}dispatch(w);}
async function finish(){if(!currentRun)return;paused=true;stopWorkers({requeue:false});currentRun.status='complete';currentRun.completed=Math.min(currentRun.completed,currentRun.target);currentRun.updatedAt=Date.now();await saveRun(currentRun);setStatus('完了','complete');renderAll();await renderHistory();window.dispatchEvent(new CustomEvent('niwara-research-updated'));}
function rateNow(){if(!currentRun)return 0;const now=performance.now(),dt=(now-lastRateAt)/1000;if(dt>=1){currentRun.__rate=(currentRun.completed-lastRateCompleted)/dt;lastRateAt=now;lastRateCompleted=currentRun.completed;}return currentRun.__rate||0;}
function renderProgress(){const r=currentRun,b=$('research-progress-bar'),t=$('research-progress-text'),m=$('research-progress-meta');if(!r){if(b)b.style.width='0%';if(t)t.textContent='未開始';if(m)m.textContent='';openBtn.textContent='環境研究';return;}const p=r.target?Math.min(100,r.completed*100/r.target):0;if(b)b.style.width=`${p}%`;if(t)t.textContent=`${fmt(r.completed)} / ${fmt(r.target)} 試合（${p.toFixed(1)}%）`;openBtn.textContent=r.status==='running'?`環境研究 ${p.toFixed(0)}%`:'環境研究';if(m)m.textContent=`${FORMAT_NAME[r.config?.format||'single']}｜${r.name}｜${r.status==='complete'?'完了':r.status==='running'?'計算中':'一時停止'}${rateNow()?`｜約 ${rateNow().toFixed(1)} 試合/秒`:''}`;}
function teamsPerBattle(format){return format==='tag'?4:2;}
function speciesRows(stats){const denom=Math.max(1,stats.battles*teamsPerBattle(stats.format||currentRun?.config?.format||'single'));return Object.entries(stats.species||{}).map(([id,s])=>({id,name:speciesName(id),usage:s.roster/denom,select:s.selected/Math.max(1,s.roster),lead:s.leads/Math.max(1,s.selected),win:s.selectedWins/Math.max(1,s.selected),kos:s.kos||0,deaths:s.deaths||0})).sort((a,b)=>b.usage-a.usage);}
function td(v){const e=document.createElement('td');e.textContent=v;return e;}
function renderSpecies(s){const body=$('research-species-body');if(!body)return;body.replaceChildren();for(const r of speciesRows(s)){const tr=document.createElement('tr');[r.name,pct(r.usage,1),pct(r.select,1),pct(r.lead,1),pct(r.win,1),fmt(r.kos),fmt(r.deaths)].forEach(v=>tr.appendChild(td(v)));body.appendChild(tr);}const sel=$('research-species-detail-select');if(sel){const old=sel.value;sel.replaceChildren();for(const r of speciesRows(s)){const o=document.createElement('option');o.value=r.id;o.textContent=r.name;sel.appendChild(o);}if([...sel.options].some(o=>o.value===old))sel.value=old;}}
function renderMoves(s){const body=$('research-moves-body');if(!body)return;body.replaceChildren();for(const[id,r]of Object.entries(s.moves||{}).sort((a,b)=>b[1].uses-a[1].uses).slice(0,100)){const tr=document.createElement('tr');[moveName(id),fmt(r.uses),pct(r.hits,r.uses),r.hits?(r.damage/r.hits).toFixed(1):'-',fmt(r.kos)].forEach(v=>tr.appendChild(td(v)));body.appendChild(tr);}}
function renderSimple(id,map,nameFn,total){const body=$(id);if(!body)return;body.replaceChildren();for(const[k,c]of Object.entries(map||{}).sort((a,b)=>b[1]-a[1]).slice(0,100)){const tr=document.createElement('tr');[nameFn(k),fmt(c),pct(c,total)].forEach(v=>tr.appendChild(td(v)));body.appendChild(tr);}}
function renderSpreads(s){const body=$('research-spreads-body');if(!body)return;body.replaceChildren();for(const[key,c]of Object.entries(s.spreads||{}).sort((a,b)=>b[1]-a[1]).slice(0,100)){const[id,nature,spread]=key.split('|'),tr=document.createElement('tr');[speciesName(id),nature,spread,fmt(c)].forEach(v=>tr.appendChild(td(v)));body.appendChild(tr);}}
function renderMatchups(s){const body=$('research-matchups-body');if(!body)return;body.replaceChildren();for(const[k,v]of Object.entries(s.matchups||{}).filter(([,v])=>v.games>=Math.max(3,s.battles*.001)).sort((a,b)=>b[1].games-a[1].games).slice(0,120)){const[a,b]=k.split('>'),tr=document.createElement('tr');[`${speciesName(a)} → ${speciesName(b)}`,fmt(v.games),pct(v.wins,v.games)].forEach(x=>tr.appendChild(td(x)));body.appendChild(tr);}}
function renderSpeciesDetail(s){const root=$('research-species-detail'),sel=$('research-species-detail-select');if(!root||!sel)return;root.replaceChildren();const id=sel.value,ss=s.species?.[id];if(!ss){root.textContent='研究結果からポケモンを選択してください。';return;}const addCard=(title,rows,heads)=>{const c=document.createElement('section');c.className='research-species-detail-card';const h=document.createElement('h4');h.textContent=title;c.appendChild(h);const table=document.createElement('table');if(heads){const tr=document.createElement('tr');heads.forEach(x=>{const th=document.createElement('th');th.textContent=x;tr.appendChild(th);});table.appendChild(tr);}rows.forEach(row=>{const tr=document.createElement('tr');row.forEach(x=>tr.appendChild(td(x)));table.appendChild(tr);});c.appendChild(table);root.appendChild(c);};
const mids=[...new Set([...Object.keys(ss.moveSets||{}),...Object.keys(ss.moves||{})])].sort((a,b)=>(ss.moveSets?.[b]||0)-(ss.moveSets?.[a]||0)||(ss.moves?.[b]?.uses||0)-(ss.moves?.[a]?.uses||0));const moveRows=mids.map(mid=>{const m=ss.moves?.[mid]||{uses:0,hits:0,kos:0};return[moveName(mid),fmt(ss.moveSets?.[mid]||0),pct(ss.moveSets?.[mid]||0,ss.roster),fmt(m.uses),pct(m.hits,m.uses),fmt(m.kos)];});addCard('技採用率・実戦使用',moveRows.length?moveRows:[['データなし','-','-','-','-','-']],['技','採用','採用率','使用','有効率','KO']);
const totalItems=Object.values(ss.items||{}).reduce((a,b)=>a+b,0);addCard('持ち物',Object.entries(ss.items||{}).sort((a,b)=>b[1]-a[1]).map(([x,c])=>[itemName(x),fmt(c),pct(c,totalItems)]),['持ち物','採用','率']);
const totalAb=Object.values(ss.abilities||{}).reduce((a,b)=>a+b,0);addCard('特性',Object.entries(ss.abilities||{}).sort((a,b)=>b[1]-a[1]).map(([x,c])=>[abilityName(x),fmt(c),pct(c,totalAb)]),['特性','採用','率']);
const matchup=Object.entries(ss.matchups||{}).sort((a,b)=>b[1].games-a[1].games).slice(0,20).map(([oid,m])=>[speciesName(oid),fmt(m.games),pct(m.wins,m.games),`${m.kos||0}/${m.deaths||0}`]);addCard('対面・同時選出結果',matchup.length?matchup:[['データなし','-','-','-']],['相手','サンプル','勝率','KO/被KO']);
$('research-species-detail-note').textContent=`${speciesName(id)}｜${FORMAT_NAME[s.format||currentRun?.config?.format||'single']}｜構築採用 ${fmt(ss.roster)} 回`;}
function renderSummary(s){const e=$('research-summary');if(!e)return;e.replaceChildren();const b=s.battles||0,vals=[['形式',FORMAT_NAME[s.format||currentRun?.config?.format||'single']],['試合数',fmt(b)],['平均ターン',b?(s.turns/b).toFixed(1):'-'],['平均交代',b?(s.switches/b).toFixed(1):'-'],['A勝率',pct(s.wins?.A||0,b)],['B勝率',pct(s.wins?.B||0,b)],['引き分け',pct(s.wins?.draw||0,b)]];for(const[k,v]of vals){const c=document.createElement('div');c.className='research-kpi';const a=document.createElement('span'),st=document.createElement('strong');a.textContent=k;st.textContent=v;c.append(a,st);e.appendChild(c);}}
function renderAll(){renderProgress();const s=currentRun?.stats||emptyStats($('research-format')?.value||'single');renderSummary(s);renderSpecies(s);renderMoves(s);renderSpreads(s);const slots=Math.max(1,s.battles*(s.format==='tag'?24:12));renderSimple('research-items-body',s.items,itemName,slots);renderSimple('research-abilities-body',s.abilities,abilityName,slots);renderMatchups(s);renderSpeciesDetail(s);$('research-pause').disabled=!currentRun||currentRun.status!=='running';$('research-resume').disabled=!currentRun||currentRun.status==='running'||currentRun.completed>=currentRun.target;}
async function renderHistory(){const runs=await dbAll(),body=$('research-history-body');if(body){body.replaceChildren();for(const r of runs.slice(0,50)){const tr=document.createElement('tr');[`${r.name} [${FORMAT_NAME[r.config?.format||'single']}]`,`v${r.version||'?'}`,`${fmt(r.completed)}/${fmt(r.target)}`,r.status==='complete'?'完了':'途中',new Date(r.updatedAt).toLocaleString('ja-JP')].forEach(v=>tr.appendChild(td(v)));const act=document.createElement('td'),load=document.createElement('button');load.className='ghost-button compact-button';load.textContent='表示';load.onclick=()=>loadRun(r.id);act.append(load);if(r.completed<r.target){const b=document.createElement('button');b.className='ghost-button compact-button';b.textContent='再開';b.onclick=async()=>{await loadRun(r.id);startRun(currentRun);};act.append(b);}const del=document.createElement('button');del.className='ghost-button compact-button danger-text';del.textContent='削除';del.onclick=async()=>{if(confirm(`「${r.name}」を削除しますか？`)){if(currentRun?.id===r.id){stopWorkers({requeue:false});currentRun=null;}await dbDelete(r.id);renderAll();renderHistory();window.dispatchEvent(new CustomEvent('niwara-research-updated'));}};act.append(del);tr.append(act);body.append(tr);}}
for(const id of['research-compare-base','research-compare-new']){const sel=$(id);if(!sel)continue;const old=sel.value;sel.replaceChildren();for(const r of runs){const o=document.createElement('option');o.value=r.id;o.textContent=`${r.name} [${FORMAT_NAME[r.config?.format||'single']}] (${fmt(r.completed)})`;sel.appendChild(o);}if(runs.some(x=>x.id===old))sel.value=old;}}
async function loadRun(id){const r=(await dbAll()).find(x=>x.id===id);if(!r)return;if(r.status==='running'){r.status='paused';if(r.inflight?.length){r.todoRanges=(r.todoRanges||[]).concat(r.inflight);r.inflight=[];}await saveRun(r);}r.config=r.config||{};r.config.format=r.config.format||r.stats?.format||'single';r.stats=r.stats||emptyStats(r.config.format);r.stats.format=r.config.format;currentRun=r;paused=true;stopWorkers({requeue:false});$('research-run-name').value=r.name||'';$('research-target').value=r.target||10000;$('research-format').value=r.config.format;$('research-ai-a').value=r.config.difficultyA||'very-strong';$('research-ai-b').value=r.config.difficultyB||'very-strong';$('research-build-mode').value=r.config.buildMode||'auto';$('research-seed').value=r.config.seed||'niwara-v12';$('research-turn-limit').value=r.config.turnLimit||200;$('research-workers').value=String(r.workers||Math.min(4,navigator.hardwareConcurrency||2));setStatus(r.status==='complete'?'完了':'保存済み結果を表示');renderAll();}
function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const safeName=s=>String(s||'niwara-research').replace(/[\\/:*?"<>|]/g,'_');const csv=v=>{const s=String(v??'');return/[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;};
function exportJson(){if(currentRun)download(`${safeName(currentRun.name)}-${currentRun.config.format}.json`,JSON.stringify(currentRun,null,2),'application/json');}
function exportCsv(){if(!currentRun)return;const s=currentRun.stats,lines=['section,species,name,metric1,metric2,metric3,metric4'];for(const r of speciesRows(s))lines.push(['species',r.name,r.name,(r.usage*100).toFixed(3),(r.select*100).toFixed(3),(r.win*100).toFixed(3),r.kos].map(csv).join(','));for(const[sid,ss]of Object.entries(s.species||{})){for(const[mid,c]of Object.entries(ss.moveSets||{}))lines.push(['species_move_adoption',speciesName(sid),moveName(mid),c,pct(c,ss.roster),'',''].map(csv).join(','));for(const[mid,m]of Object.entries(ss.moves||{}))lines.push(['species_move_use',speciesName(sid),moveName(mid),m.uses,m.hits,m.damage,m.kos].map(csv).join(','));for(const[id,c]of Object.entries(ss.items||{}))lines.push(['species_item',speciesName(sid),itemName(id),c,'','',''].map(csv).join(','));for(const[id,c]of Object.entries(ss.abilities||{}))lines.push(['species_ability',speciesName(sid),abilityName(id),c,'','',''].map(csv).join(','));}download(`${safeName(currentRun.name)}-${currentRun.config.format}.csv`,lines.join('\n'),'text/csv;charset=utf-8');}
async function compareRuns(){const runs=await dbAll(),a=runs.find(r=>r.id===$('research-compare-base').value),b=runs.find(r=>r.id===$('research-compare-new').value),body=$('research-compare-body');body.replaceChildren();if(!a||!b)return;if((a.config?.format||'single')!==(b.config?.format||'single')){const tr=document.createElement('tr');const c=document.createElement('td');c.colSpan=7;c.textContent='異なるバトル形式同士は直接比較できません。';tr.append(c);body.append(tr);return;}const ar=Object.fromEntries(speciesRows(a.stats).map(x=>[x.id,x])),br=Object.fromEntries(speciesRows(b.stats).map(x=>[x.id,x]));for(const id of[...new Set([...Object.keys(ar),...Object.keys(br)])].sort((x,y)=>Math.abs((br[y]?.usage||0)-(ar[y]?.usage||0))-Math.abs((br[x]?.usage||0)-(ar[x]?.usage||0)))){const x=ar[id]||{},y=br[id]||{},tr=document.createElement('tr');[speciesName(id),pct(x.usage||0,1),pct(y.usage||0,1),`${(((y.usage||0)-(x.usage||0))*100).toFixed(1)}pt`,pct(x.win||0,1),pct(y.win||0,1),`${(((y.win||0)-(x.win||0))*100).toFixed(1)}pt`].forEach(v=>tr.appendChild(td(v)));body.appendChild(tr);}}
async function clearAll(){paused=true;stopWorkers({requeue:false});currentRun=null;try{await saveChain;}catch(_){}await new Promise(res=>{const r=indexedDB.deleteDatabase(DB_NAME);r.onsuccess=r.onerror=r.onblocked=()=>res();});saveChain=Promise.resolve();renderAll();await renderHistory();setStatus('環境研究データを初期化しました');window.dispatchEvent(new CustomEvent('niwara-research-updated'));}
function openResearch(){previousScreen=[...document.querySelectorAll('section.screen')].find(s=>!s.classList.contains('hidden')&&s!==screen)||$('builder-screen');document.querySelectorAll('section.screen').forEach(s=>s.classList.add('hidden'));screen.classList.remove('hidden');renderAll();renderHistory();}
function closeResearch(){screen.classList.add('hidden');(previousScreen||$('builder-screen')).classList.remove('hidden');}
openBtn.onclick=openResearch;closeBtn.onclick=closeResearch;$('research-start').onclick=async()=>{currentRun=makeRun(configFromUI());await startRun(currentRun);};$('research-pause').onclick=pause;$('research-resume').onclick=()=>currentRun&&startRun(currentRun);$('research-export-json').onclick=exportJson;$('research-export-csv').onclick=exportCsv;$('research-compare-button').onclick=compareRuns;$('research-species-detail-select').onchange=()=>renderSpeciesDetail(currentRun?.stats||emptyStats());
document.querySelectorAll('[data-research-target]').forEach(b=>b.onclick=()=>{$('research-target').value=b.dataset.researchTarget;});const ws=$('research-workers');if(ws){const n=String(Math.min(4,navigator.hardwareConcurrency||2));if([...ws.options].some(o=>o.value===n))ws.value=n;}
setInterval(()=>{if(currentRun?.status==='running')renderProgress();},1000);window.addEventListener('pagehide',()=>{if(currentRun?.status==='running'){for(const p of pending.values())currentRun.todoRanges.push({start:p.start,count:p.count});currentRun.inflight=[];currentRun.status='paused';currentRun.updatedAt=Date.now();saveRun(currentRun).catch(()=>{});}stopWorkers({requeue:false});});
renderAll();renderHistory().catch(console.warn);
window.NIWARA_RESEARCH=Object.freeze({version:VERSION,get currentRun(){return currentRun;},pause,start:()=>currentRun&&startRun(currentRun),clearAll,allRuns:dbAll,latestByFormat:async format=>(await dbAll()).find(r=>(r.config?.format||'single')===format&&r.completed>0)||null});
})();
